local util = require("functions/util")

util.regroup.createSubgroup("bio-seed", "bio-industries", "raw-01")
util.regroup.createSubgroup("bio-seedling", "bio-industries", "raw-02")
util.regroup.createSubgroup("bio-wood", "bio-industries", "raw-03")
util.regroup.createSubgroup("bio-chemical", "bio-industries", "raw-04")
util.regroup.createSubgroup("bio-stone", "bio-industries", "raw-05")
util.regroup.createSubgroup("bio-fertilizer", "bio-industries", "raw-06")
util.regroup.createSubgroup("bio-terraform", "bio-industries", "raw-07")
util.regroup.createSubgroup("bio-biomass", "bio-industries", "raw-08")
util.regroup.createSubgroup("bio-petrochemistry", "bio-industries", "raw-09")
util.regroup.createSubgroup("bio-purified", "bio-industries", "raw-10")

-- bio-seed
util.regroup.setSubgroupToPrototype("bi-seed", "bio-seed", "01")
util.regroup.setSubgroupToPrototype("bi-seed-1", "bio-seed", "02")
util.regroup.setSubgroupToPrototype("bi-seed-2", "bio-seed", "03")
util.regroup.setSubgroupToPrototype("bi-seed-3", "bio-seed", "04")
util.regroup.setSubgroupToPrototype("bi-seed-4", "bio-seed", "05")

-- bio-seedling
util.regroup.setSubgroupToPrototype("seedling", "bio-seedling", "01")
util.regroup.setSubgroupToPrototype("bi-seedling-1", "bio-seedling", "01")
util.regroup.setSubgroupToPrototype("bi-seedling-2", "bio-seedling", "01")
util.regroup.setSubgroupToPrototype("bi-seedling-3", "bio-seedling", "01")
util.regroup.setSubgroupToPrototype("bi-seedling-4", "bio-seedling", "01")

-- bio-wood
util.regroup.setSubgroupToPrototype("wood", "bio-wood", "01")
util.regroup.setSubgroupToPrototype("kr-grow-wood-with-water", "bio-wood", "02")
util.regroup.setSubgroupToPrototype("kr-grow-wood-with-sand", "bio-wood", "03")
util.regroup.setSubgroupToPrototype("kr-grow-wood-plus", "bio-wood", "04")
util.regroup.setSubgroupToPrototype("bi-logs-1", "bio-wood", "05")
util.regroup.setSubgroupToPrototype("bi-logs-2", "bio-wood", "06")
util.regroup.setSubgroupToPrototype("bi-logs-3", "bio-wood", "07")
util.regroup.setSubgroupToPrototype("bi-logs-4", "bio-wood", "08")
util.regroup.setSubgroupToPrototype("bi-wood-from-pulp", "bio-wood", "08")

-- bio-chemical
util.regroup.setSubgroupToPrototype("bi-woodpulp", "bio-chemical", "01")
util.regroup.setSubgroupToPrototype("resin", "bio-chemical", "02")
util.regroup.setSubgroupToPrototype("bi-resin-pulp", "bio-chemical", "03")
util.regroup.setSubgroupToPrototype("wood-bricks", "bio-chemical", "04")
util.regroup.setSubgroupToPrototype("bi-wood-fuel-brick", "bio-chemical", "05")
util.regroup.setSubgroupToPrototype("bi-solid-fuel", "bio-chemical", "06")
util.regroup.setSubgroupToPrototype("bi-ash", "bio-chemical", "07")
util.regroup.setSubgroupToPrototype("bi-ash-1", "bio-chemical", "08")
util.regroup.setSubgroupToPrototype("bi-ash-2", "bio-chemical", "09")
util.regroup.setSubgroupToPrototype("wood-charcoal", "bio-chemical", "10")
util.regroup.setSubgroupToPrototype("bi-charcoal-1", "bio-chemical", "11")
util.regroup.setSubgroupToPrototype("bi-charcoal-2", "bio-chemical", "12")
util.regroup.setSubgroupToPrototype("wood-charcoal", "bio-chemical", "13")
util.regroup.setSubgroupToPrototype("bi-charcoal-1", "bio-chemical", "14")
util.regroup.setSubgroupToPrototype("bi-charcoal-2", "bio-chemical", "15")
util.regroup.setSubgroupToPrototype("bi-coal-1", "bio-chemical", "16")
util.regroup.setSubgroupToPrototype("bi-coal-2", "bio-chemical", "17")
util.regroup.setSubgroupToPrototype("pellet-coke", "bio-chemical", "18")
util.regroup.setSubgroupToPrototype("bi-coke-coal", "bio-chemical", "19")
util.regroup.setSubgroupToPrototype("bi-pellet-coke", "bio-chemical", "20")

-- bio-stone
util.regroup.setSubgroupToPrototype("sand", "bio-stone", "01")
util.regroup.setSubgroupToPrototype("sand-from-stone", "bio-stone", "02")
util.regroup.setSubgroupToPrototype("bi-sand", "bio-stone", "03")
util.regroup.setSubgroupToPrototype("stone-crushed", "bio-stone", "04")
util.regroup.setSubgroupToPrototype("bi-crushed-stone-1", "bio-stone", "05")
util.regroup.setSubgroupToPrototype("bi-crushed-stone-2", "bio-stone", "06")
util.regroup.setSubgroupToPrototype("bi-crushed-stone-3", "bio-stone", "07")
util.regroup.setSubgroupToPrototype("bi-crushed-stone-4", "bio-stone", "08")
util.regroup.setSubgroupToPrototype("bi-crushed-stone-5", "bio-stone", "09")
util.regroup.setSubgroupToPrototype("stone", "bio-stone", "10")
util.regroup.setSubgroupToPrototype("fu_materials_stone", "bio-stone", "11")
util.regroup.setSubgroupToPrototype("fu_mining_recipe", "bio-stone", "12")
util.regroup.setSubgroupToPrototype("fu_crush_stone_recipe", "bio-stone", "13")
util.regroup.setSubgroupToPrototype("fu_extract_stone_recipe", "bio-stone", "14")
util.regroup.setSubgroupToPrototype("stone-brick", "bio-stone", "15")
util.regroup.setSubgroupToPrototype("bi-stone-brick", "bio-stone", "16")

-- bio-fertilizer
util.regroup.setSubgroupToPrototype("fertilizer", "bio-fertilizer", "01")
util.regroup.setSubgroupToPrototype("se-kr-fertilizer-with-nutrients", "bio-fertilizer", "02")
util.regroup.setSubgroupToPrototype("bi-fertilizer-1", "bio-fertilizer", "03")
util.regroup.setSubgroupToPrototype("bi-adv-fertilizer", "bio-fertilizer", "04")
util.regroup.setSubgroupToPrototype("bi-adv-fertilizer-2", "bio-fertilizer", "05")

-- bio-terraform
util.regroup.setSubgroupToPrototype("bi-arboretum-area", "bio-terraform", "01")
util.regroup.setSubgroupToPrototype("bi-arboretum", "bio-terraform", "02")
util.regroup.setSubgroupToPrototype("bi-arboretum-r1", "bio-terraform", "03")
util.regroup.setSubgroupToPrototype("bi-arboretum-r2", "bio-terraform", "04")
util.regroup.setSubgroupToPrototype("bi-arboretum-r3", "bio-terraform", "05")
util.regroup.setSubgroupToPrototype("bi-arboretum-r4", "bio-terraform", "06")
util.regroup.setSubgroupToPrototype("bi-arboretum-r5", "bio-terraform", "07")

-- bio-biomass
util.regroup.setSubgroupToPrototype("bi-biomass-1", "bio-biomass", "01")
util.regroup.setSubgroupToPrototype("bi-biomass-2", "bio-biomass", "02")
util.regroup.setSubgroupToPrototype("bi-biomass-3", "bio-biomass", "03")

-- bio-petrochemistry
util.regroup.setSubgroupToPrototype("bi-plastic-1", "bio-petrochemistry", "01")
util.regroup.setSubgroupToPrototype("bi-plastic-2", "bio-petrochemistry", "02")
util.regroup.setSubgroupToPrototype("bi-battery", "bio-petrochemistry", "03")
util.regroup.setSubgroupToPrototype("bi-sulfur", "bio-petrochemistry", "04")
util.regroup.setSubgroupToPrototype("bi-cellulose", "bio-petrochemistry", "05")
util.regroup.setSubgroupToPrototype("bi-cellulose-1", "bio-petrochemistry", "06")
util.regroup.setSubgroupToPrototype("bi-cellulose-2", "bio-petrochemistry", "07")
util.regroup.setSubgroupToPrototype("bi-basic-gas-processing", "bio-petrochemistry", "08")
util.regroup.setSubgroupToPrototype("bi-acid", "bio-petrochemistry", "09")
util.regroup.setSubgroupToPrototype("bi-biomass-conversion-1", "bio-petrochemistry", "10")
util.regroup.setSubgroupToPrototype("bi-biomass-conversion-2", "bio-petrochemistry", "11")
util.regroup.setSubgroupToPrototype("bi-biomass-conversion-3", "bio-petrochemistry", "12")
util.regroup.setSubgroupToPrototype("bi-biomass-conversion-4", "bio-petrochemistry", "13")

-- bio-purified
util.regroup.setSubgroupToPrototype("bi-purified-air-0", "bio-purified", "01")
util.regroup.setSubgroupToPrototype("bi-purified-air-1", "bio-purified", "02")
util.regroup.setSubgroupToPrototype("bi-purified-air-2", "bio-purified", "03")
