local util = require("functions/util")

util.regroup.createSubgroup("combat-tool", "combat", "raw-01")
util.regroup.createSubgroup("combat-defensive-structure", "combat", "raw-02")
util.regroup.createSubgroup("combat-radars-and-rockets", "combat", "raw-03")
util.regroup.createSubgroup("combat-defensive-tool", "combat", "raw-04")
util.regroup.createSubgroup("combat-dart", "combat", "raw-05")
util.regroup.createSubgroup("combat-firearm", "combat", "raw-06")
util.regroup.createSubgroup("combat-shotgun", "combat", "raw-07")
util.regroup.createSubgroup("combat-large-rifle", "combat", "raw-08")
util.regroup.createSubgroup("combat-rifle", "combat", "raw-09")
util.regroup.createSubgroup("combat-flamethrower", "combat", "raw-10")
util.regroup.createSubgroup("combat-se-gun", "combat", "raw-11")
util.regroup.createSubgroup("combat-capsule", "combat", "raw-12")
util.regroup.createSubgroup("combat-cannon", "combat", "raw-13")
util.regroup.createSubgroup("combat-rocket", "combat", "raw-14")
util.regroup.createSubgroup("combat-railgun", "combat", "raw-15")
util.regroup.createSubgroup("combat-rocket-turret", "combat", "raw-16")
util.regroup.createSubgroup("combat-laser", "combat", "raw-17")
util.regroup.createSubgroup("combat-artillery", "combat", "raw-18")
util.regroup.createSubgroup("combat-surface-defense", "combat", "raw-19")
util.regroup.createSubgroup("combat-grenade", "combat", "raw-20")
util.regroup.createSubgroup("combat-biter-capsule", "combat", "raw-21")

-- combat-tool
util.regroup.setSubgroupToPrototype("repair-pack", "combat-tool", "01")
util.regroup.setSubgroupToPrototype("copper-repair-pack", "combat-tool", "02")
util.regroup.setSubgroupToPrototype("copper-repair-recipe", "combat-tool", "03")
util.regroup.setSubgroupToPrototype("steel-repair-pack", "combat-tool", "04")
util.regroup.setSubgroupToPrototype("steel-repair-recipe", "combat-tool", "05")
util.regroup.setSubgroupToPrototype("field-repair-pack", "combat-tool", "06")
util.regroup.setSubgroupToPrototype("field-repair-recipe", "combat-tool", "07")
util.regroup.setSubgroupToPrototype("multitool-repair-pack", "combat-tool", "08")
util.regroup.setSubgroupToPrototype("multitool-repair-recipe", "combat-tool", "09")
util.regroup.setSubgroupToPrototype("first-aid-kit", "combat-tool", "10")
util.regroup.setSubgroupToPrototype("first-aid-kit-fish", "combat-tool", "11")
util.regroup.setSubgroupToPrototype("se-medpack", "combat-tool", "12")
util.regroup.setSubgroupToPrototype("se-medpack-plastic", "combat-tool", "13")
util.regroup.setSubgroupToPrototype("se-medpack-2", "combat-tool", "14")
util.regroup.setSubgroupToPrototype("se-medpack-3", "combat-tool", "15")
util.regroup.setSubgroupToPrototype("se-medpack-4", "combat-tool", "16")
util.regroup.setSubgroupToPrototype("gun-nano-emitter", "combat-tool", "17")
util.regroup.setSubgroupToPrototype("ammo-nano-constructors", "combat-tool", "18")
util.regroup.setSubgroupToPrototype("ammo-nano-termites", "combat-tool", "19")

-- combat-defensive-structure
util.regroup.setSubgroupToPrototype("bi-wooden-fence", "combat-defensive-structure", "01")
util.regroup.setSubgroupToPrototype("stone-wall", "combat-defensive-structure", "02")
util.regroup.setSubgroupToPrototype("concrete-wall", "combat-defensive-structure", "03")
util.regroup.setSubgroupToPrototype("steel-wall", "combat-defensive-structure", "04")
util.regroup.setSubgroupToPrototype("mending-wall-rampant-arsenal", "combat-defensive-structure", "05")
util.regroup.setSubgroupToPrototype("reinforced-wall-rampant-arsenal", "combat-defensive-structure", "06")
util.regroup.setSubgroupToPrototype("gate", "combat-defensive-structure", "07")
util.regroup.setSubgroupToPrototype("mending-gate-rampant-arsenal", "combat-defensive-structure", "08")
util.regroup.setSubgroupToPrototype("reinforced-gate-rampant-arsenal", "combat-defensive-structure", "09")
util.regroup.setSubgroupToPrototype("shield-projector", "combat-defensive-structure", "10")

-- radars-and-rockets
util.regroup.setSubgroupToPrototype("kr-sentinel", "combat-radars-and-rockets", "01")
util.regroup.setSubgroupToPrototype("radar", "combat-radars-and-rockets", "02")
util.regroup.setSubgroupToPrototype("advanced-radar", "combat-radars-and-rockets", "03")
util.regroup.setSubgroupToPrototype("rocket-silo", "combat-radars-and-rockets", "04")
util.regroup.setSubgroupToPrototype("kr-intergalactic-transceiver", "combat-radars-and-rockets", "05")

-- combat-defensive-tool
util.regroup.setSubgroupToPrototype("medic-item-rampant-arsenal", "combat-defensive-tool", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-medic-item-rampant-arsenal", "combat-defensive-tool", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-medic-item-rampant-arsenal", "combat-defensive-tool", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-medic-item-rampant-arsenal", "combat-defensive-tool", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-medic-item-rampant-arsenal", "combat-defensive-tool", "05")
util.regroup.setSubgroupToPrototype("artillery-targeting-remote", "combat-defensive-tool", "06")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-artillery-targeter-atomic-bomb", "combat-defensive-tool", "07")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-artillery-targeter-se-iridium-piledriver", "combat-defensive-tool", "08")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-artillery-targeter-antimatter-rocket", "combat-defensive-tool", "09")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-artillery-targeter-se-plague-bomb", "combat-defensive-tool", "10")
util.regroup.setSubgroupToPrototype("orbital-ion-cannon", "combat-defensive-tool", "11")
util.regroup.setSubgroupToPrototype("artillery-bombardment-remote", "combat-defensive-tool", "12")
util.regroup.setSubgroupToPrototype("smart-artillery-bombardment-remote", "combat-defensive-tool", "13")
util.regroup.setSubgroupToPrototype("smart-artillery-exploration-remote", "combat-defensive-tool", "14")

-- combat-dart
util.regroup.setSubgroupToPrototype("bi-dart-turret", "combat-dart", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-bi-dart-turret", "combat-dart", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-bi-dart-turret", "combat-dart", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-bi-dart-turret", "combat-dart", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-bi-dart-turret", "combat-dart", "05")
util.regroup.setSubgroupToPrototype("bi-dart-rifle", "combat-dart", "06")
util.regroup.setSubgroupToPrototype("bi-dart-magazine-basic", "combat-dart", "07")
util.regroup.setSubgroupToPrototype("bi-dart-magazine-standard", "combat-dart", "08")
util.regroup.setSubgroupToPrototype("bi-dart-magazine-enhanced", "combat-dart", "09")
util.regroup.setSubgroupToPrototype("bi-dart-magazine-poison", "combat-dart", "10")
util.regroup.setSubgroupToPrototype("bi-seed-bomb-basic", "combat-dart", "11")
util.regroup.setSubgroupToPrototype("bi-seed-bomb-standard", "combat-dart", "12")
util.regroup.setSubgroupToPrototype("bi-seed-bomb-advanced", "combat-dart", "13")

-- combat-firearm
util.regroup.setSubgroupToPrototype("pistol", "combat-firearm", "01")
util.regroup.setSubgroupToPrototype("firearm-magazine", "combat-firearm", "02")
util.regroup.setSubgroupToPrototype("pistol-magazine-bismuth", "combat-firearm", "03")
util.regroup.setSubgroupToPrototype("high-capacity-firearm-magazine", "combat-firearm", "04")
util.regroup.setSubgroupToPrototype("piercing-rounds-magazine", "combat-firearm", "05")
util.regroup.setSubgroupToPrototype("high-capacity-piercing-rounds-magazine", "combat-firearm", "06")

-- combat-shotgun
util.regroup.setSubgroupToPrototype("shotgun-item-rampant-arsenal", "combat-shotgun", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-shotgun-item-rampant-arsenal", "combat-shotgun", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-shotgun-item-rampant-arsenal", "combat-shotgun", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-shotgun-item-rampant-arsenal", "combat-shotgun", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-shotgun-item-rampant-arsenal", "combat-shotgun", "05")
util.regroup.setSubgroupToPrototype("shotgun", "combat-shotgun", "06")
util.regroup.setSubgroupToPrototype("combat-shotgun", "combat-shotgun", "07")
util.regroup.setSubgroupToPrototype("shotgun-shell", "combat-shotgun", "08")
util.regroup.setSubgroupToPrototype("high-capacity-shotgun-shell", "combat-shotgun", "09")
util.regroup.setSubgroupToPrototype("piercing-shotgun-shell", "combat-shotgun", "10")
util.regroup.setSubgroupToPrototype("high-capacity-piercing-shotgun-shell", "combat-shotgun", "11")
util.regroup.setSubgroupToPrototype("uranium-shotgun-shell", "combat-shotgun", "12")
util.regroup.setSubgroupToPrototype("uranium-shotgun-recipe", "combat-shotgun", "13")
util.regroup.setSubgroupToPrototype("high-capacity-uranium-shotgun-shell", "combat-shotgun", "14")
util.regroup.setSubgroupToPrototype("high-capacity-uranium-shotgun-recipe", "combat-shotgun", "15")
util.regroup.setSubgroupToPrototype("bio-shotgun-ammo-rampant-arsenal", "combat-shotgun", "16")
util.regroup.setSubgroupToPrototype("he-shotgun-ammo-rampant-arsenal", "combat-shotgun", "17")
util.regroup.setSubgroupToPrototype("incendiary-shotgun-ammo-rampant-arsenal", "combat-shotgun", "18")
util.regroup.setSubgroupToPrototype("uranium-shotgun-ammo-rampant-arsenal", "combat-shotgun", "19")

-- combat-large-rifle
util.regroup.setSubgroupToPrototype("anti-material-rifle", "combat-large-rifle", "01")
util.regroup.setSubgroupToPrototype("anti-material-rifle-magazine", "combat-large-rifle", "02")
util.regroup.setSubgroupToPrototype("armor-piercing-anti-material-rifle-magazine", "combat-large-rifle", "03")
util.regroup.setSubgroupToPrototype("explosive-rounds-anti-material-rifle-magazine", "combat-large-rifle", "04")
util.regroup.setSubgroupToPrototype("uranium-anti-material-rifle-magazine", "combat-large-rifle", "05")
util.regroup.setSubgroupToPrototype("imersite-anti-material-rifle-magazine", "combat-large-rifle", "06")

-- combat-rifle
util.regroup.setSubgroupToPrototype("gun-turret", "combat-rifle", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-gun-turret", "combat-rifle", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-gun-turret", "combat-rifle", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-gun-turret", "combat-rifle", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-gun-turret", "combat-rifle", "05")
util.regroup.setSubgroupToPrototype("gun-item-rampant-arsenal", "combat-rifle", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-gun-item-rampant-arsenal", "combat-rifle", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-gun-item-rampant-arsenal", "combat-rifle", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-gun-item-rampant-arsenal", "combat-rifle", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-gun-item-rampant-arsenal", "combat-rifle", "10")
util.regroup.setSubgroupToPrototype("submachine-gun", "combat-rifle", "11")
util.regroup.setSubgroupToPrototype("minigun-gun-rampant-arsenal", "combat-rifle", "12")
util.regroup.setSubgroupToPrototype("rifle-magazine", "combat-rifle", "13")
util.regroup.setSubgroupToPrototype("rifle-magazine-bismuth", "combat-rifle", "14")
util.regroup.setSubgroupToPrototype("armor-piercing-rifle-magazine", "combat-rifle", "15")
util.regroup.setSubgroupToPrototype("explosive-rounds-rifle-magazine", "combat-rifle", "16")
util.regroup.setSubgroupToPrototype("uranium-rifle-magazine", "combat-rifle", "17")
util.regroup.setSubgroupToPrototype("high-capacity-uranium-rounds-magazine", "combat-rifle", "18")
util.regroup.setSubgroupToPrototype("imersite-rifle-magazine", "combat-rifle", "19")
util.regroup.setSubgroupToPrototype("water-magazine", "combat-rifle", "20")
util.regroup.setSubgroupToPrototype("water-recipe", "combat-rifle", "21")
util.regroup.setSubgroupToPrototype("sp-rounds-magazine", "combat-rifle", "22")
util.regroup.setSubgroupToPrototype("sp-ammo-recipe", "combat-rifle", "23")
util.regroup.setSubgroupToPrototype("high-capacity-sp-rounds-magazine", "combat-rifle", "24")
util.regroup.setSubgroupToPrototype("high-capacity-sp-ammo-recipe", "combat-rifle", "25")
util.regroup.setSubgroupToPrototype("tungsten-rounds-magazine", "combat-rifle", "26")
util.regroup.setSubgroupToPrototype("tungsten-ammo-recipe", "combat-rifle", "27")
util.regroup.setSubgroupToPrototype("high-capacity-tungsten-rounds-magazine", "combat-rifle", "28")
util.regroup.setSubgroupToPrototype("high-capacity-tungsten-ammo-recipe", "combat-rifle", "29")
util.regroup.setSubgroupToPrototype("fmj-rounds-magazine", "combat-rifle", "30")
util.regroup.setSubgroupToPrototype("fmj-ammo-recipe", "combat-rifle", "31")
util.regroup.setSubgroupToPrototype("high-capacity-fmj-rounds-magazine", "combat-rifle", "32")
util.regroup.setSubgroupToPrototype("high-capacity-fmj-ammo-recipe", "combat-rifle", "33")
util.regroup.setSubgroupToPrototype("cryonite-rounds-magazine", "combat-rifle", "34")
util.regroup.setSubgroupToPrototype("cryonite-ammo-recipe", "combat-rifle", "35")
util.regroup.setSubgroupToPrototype("high-capacity-cryonite-rounds-magazine", "combat-rifle", "36")
util.regroup.setSubgroupToPrototype("high-capacity-cryonite-ammo-recipe", "combat-rifle", "37")
util.regroup.setSubgroupToPrototype("cryonite-rounds-magazine", "combat-rifle", "38")
util.regroup.setSubgroupToPrototype("cryonite-ammo-recipe", "combat-rifle", "39")
util.regroup.setSubgroupToPrototype("high-capacity-cryonite-rounds-magazine", "combat-rifle", "40")
util.regroup.setSubgroupToPrototype("high-capacity-cryonite-ammo-recipe", "combat-rifle", "41")
util.regroup.setSubgroupToPrototype("vulcanite-rounds-magazine", "combat-rifle", "42")
util.regroup.setSubgroupToPrototype("vulcanite-ammo-recipe", "combat-rifle", "43")
util.regroup.setSubgroupToPrototype("high-capacity-vulcanite-rounds-magazine", "combat-rifle", "44")
util.regroup.setSubgroupToPrototype("high-capacity-vulcanite-ammo-recipe", "combat-rifle", "45")
util.regroup.setSubgroupToPrototype("beryllium-rounds-magazine", "combat-rifle", "46")
util.regroup.setSubgroupToPrototype("beryllium-ammo-recipe", "combat-rifle", "47")
util.regroup.setSubgroupToPrototype("high-capacity-beryllium-rounds-magazine", "combat-rifle", "48")
util.regroup.setSubgroupToPrototype("high-capacity-beryllium-ammo-recipe", "combat-rifle", "49")
util.regroup.setSubgroupToPrototype("naquium-rounds-magazine", "combat-rifle", "50")
util.regroup.setSubgroupToPrototype("naquium-ammo-recipe", "combat-rifle", "51")
util.regroup.setSubgroupToPrototype("high-capacity-naquium-rounds-magazine", "combat-rifle", "52")
util.regroup.setSubgroupToPrototype("high-capacity-naquium-ammo-recipe", "combat-rifle", "53")
util.regroup.setSubgroupToPrototype("iridium-rounds-magazine", "combat-rifle", "54")
util.regroup.setSubgroupToPrototype("iridium-ammo-recipe", "combat-rifle", "55")
util.regroup.setSubgroupToPrototype("high-capacity-iridium-rounds-magazine", "combat-rifle", "56")
util.regroup.setSubgroupToPrototype("high-capacity-iridium-ammo-recipe", "combat-rifle", "57")
util.regroup.setSubgroupToPrototype("fire-rounds-magazine", "combat-rifle", "58")
util.regroup.setSubgroupToPrototype("fire-ammo-recipe", "combat-rifle", "59")
util.regroup.setSubgroupToPrototype("high-capacity-fire-rounds-magazine", "combat-rifle", "60")
util.regroup.setSubgroupToPrototype("high-capacity-fire-ammo-recipe", "combat-rifle", "61")
util.regroup.setSubgroupToPrototype("acid-rounds-magazine", "combat-rifle", "62")
util.regroup.setSubgroupToPrototype("acid-ammo-recipe", "combat-rifle", "63")
util.regroup.setSubgroupToPrototype("high-capacity-acid-rounds-magazine", "combat-rifle", "64")
util.regroup.setSubgroupToPrototype("high-capacity-acid-ammo-recipe", "combat-rifle", "65")
util.regroup.setSubgroupToPrototype("he-rounds-magazine", "combat-rifle", "66")
util.regroup.setSubgroupToPrototype("he-ammo-recipe", "combat-rifle", "67")
util.regroup.setSubgroupToPrototype("high-capacity-he-rounds-magazine", "combat-rifle", "68")
util.regroup.setSubgroupToPrototype("high-capacity-he-ammo-recipe", "combat-rifle", "69")
util.regroup.setSubgroupToPrototype("bio-magazine-ammo-rampant-arsenal", "combat-rifle", "70")
util.regroup.setSubgroupToPrototype("he-magazine-ammo-rampant-arsenal", "combat-rifle", "71")
util.regroup.setSubgroupToPrototype("incendiary-magazine-ammo-rampant-arsenal", "combat-rifle", "72")

-- combat-flamethrower
util.regroup.setSubgroupToPrototype("flamethrower-turret", "combat-flamethrower", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-flamethrower-turret", "combat-flamethrower", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-flamethrower-turret", "combat-flamethrower", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-flamethrower-turret", "combat-flamethrower", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-flamethrower-turret", "combat-flamethrower", "05")
util.regroup.setSubgroupToPrototype("acid-cannon-rampant-arsenal", "combat-flamethrower", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "10")
util.regroup.setSubgroupToPrototype("suppression-cannon-item-rampant-arsenal", "combat-flamethrower", "11")
util.regroup.setSubgroupToPrototype("flamethrower", "combat-flamethrower", "12")
util.regroup.setSubgroupToPrototype("flamethrower-ammo", "combat-flamethrower", "13")
util.regroup.setSubgroupToPrototype("napalm-ammo-rampant-arsenal", "combat-flamethrower", "14")

-- combat-capsule
util.regroup.setSubgroupToPrototype("capsule-item-rampant-arsenal", "combat-capsule", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-capsule-item-rampant-arsenal", "combat-capsule", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-capsule-item-rampant-arsenal", "combat-capsule", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-capsule-item-rampant-arsenal", "combat-capsule", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-capsule-item-rampant-arsenal", "combat-capsule", "05")
util.regroup.setSubgroupToPrototype("lite-artillery-turret-rampant-arsenal", "combat-capsule", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "10")
util.regroup.setSubgroupToPrototype("artillery-targeting-remote-rampant-arsenal", "combat-capsule", "11")
util.regroup.setSubgroupToPrototype("mortar-gun-rampant-arsenal", "combat-capsule", "12")
util.regroup.setSubgroupToPrototype("grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "13")
util.regroup.setSubgroupToPrototype("bio-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "14")
util.regroup.setSubgroupToPrototype("he-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "15")
util.regroup.setSubgroupToPrototype("incendiary-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "16")
util.regroup.setSubgroupToPrototype("cluster-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "17")
util.regroup.setSubgroupToPrototype("poison-capsule-ammo-rampant-arsenal", "combat-capsule", "18")
util.regroup.setSubgroupToPrototype("toxic-capsule-ammo-rampant-arsenal", "combat-capsule", "19")
util.regroup.setSubgroupToPrototype("slowdown-capsule-ammo-rampant-arsenal", "combat-capsule", "20")
util.regroup.setSubgroupToPrototype("paralysis-capsule-ammo-rampant-arsenal", "combat-capsule", "21")
util.regroup.setSubgroupToPrototype("repair-capsule-ammo-rampant-arsenal", "combat-capsule", "22")
util.regroup.setSubgroupToPrototype("defender-capsule-ammo-rampant-arsenal", "combat-capsule", "23")
util.regroup.setSubgroupToPrototype("distractor-capsule-ammo-rampant-arsenal", "combat-capsule", "24")
util.regroup.setSubgroupToPrototype("destroyer-capsule-ammo-rampant-arsenal", "combat-capsule", "25")
util.regroup.setSubgroupToPrototype("self-repair-capsule-ammo-rampant-arsenal", "combat-capsule", "26")
util.regroup.setSubgroupToPrototype("land-mine", "combat-capsule", "27")
util.regroup.setSubgroupToPrototype("bio-landmine-rampant-arsenal", "combat-capsule", "28")
util.regroup.setSubgroupToPrototype("he-landmine-rampant-arsenal", "combat-capsule", "29")
util.regroup.setSubgroupToPrototype("incendiary-landmine-rampant-arsenal", "combat-capsule", "30")
util.regroup.setSubgroupToPrototype("nuclear-landmine-rampant-arsenal", "combat-capsule", "31")
util.regroup.setSubgroupToPrototype("landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "32")
util.regroup.setSubgroupToPrototype("bio-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "33")
util.regroup.setSubgroupToPrototype("he-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "34")
util.regroup.setSubgroupToPrototype("incendiary-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "35")
util.regroup.setSubgroupToPrototype("nuclear-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "36")

-- se-gun
util.regroup.setSubgroupToPrototype("se-railgun", "combat-se-gun", "01")
util.regroup.setSubgroupToPrototype("se-railgun-ammo", "combat-se-gun", "02")
util.regroup.setSubgroupToPrototype("impulse-rifle", "combat-se-gun", "03")
util.regroup.setSubgroupToPrototype("impulse-rifle-ammo", "combat-se-gun", "04")
util.regroup.setSubgroupToPrototype("se-cryogun", "combat-se-gun", "05")
util.regroup.setSubgroupToPrototype("se-cryogun-ammo", "combat-se-gun", "06")
util.regroup.setSubgroupToPrototype("se-biogun", "combat-se-gun", "07")
util.regroup.setSubgroupToPrototype("se-bloater-ammo", "combat-se-gun", "08")
util.regroup.setSubgroupToPrototype("se-pheromone-ammo", "combat-se-gun", "09")
util.regroup.setSubgroupToPrototype("se-tesla-gun", "combat-se-gun", "10")
util.regroup.setSubgroupToPrototype("se-tesla-ammo", "combat-se-gun", "11")
util.regroup.setSubgroupToPrototype("grappling-gun", "combat-se-gun", "12")
util.regroup.setSubgroupToPrototype("grappling-gun-ammo", "combat-se-gun", "13")

-- cannon-shell
util.regroup.setSubgroupToPrototype("cannon-item-rampant-arsenal", "combat-cannon", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-cannon-item-rampant-arsenal", "combat-cannon", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-cannon-item-rampant-arsenal", "combat-cannon", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-cannon-item-rampant-arsenal", "combat-cannon", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-cannon-item-rampant-arsenal", "combat-cannon", "05")
util.regroup.setSubgroupToPrototype("rapid-cannon-item-rampant-arsenal", "combat-cannon", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "10")
util.regroup.setSubgroupToPrototype("cannon-shell", "combat-cannon", "11")
util.regroup.setSubgroupToPrototype("explosive-cannon-shell", "combat-cannon", "12")
util.regroup.setSubgroupToPrototype("uranium-cannon-shell", "combat-cannon", "13")
util.regroup.setSubgroupToPrototype("explosive-uranium-cannon-shell", "combat-cannon", "14")
util.regroup.setSubgroupToPrototype("bio-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "15")
util.regroup.setSubgroupToPrototype("he-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "16")
util.regroup.setSubgroupToPrototype("incendiary-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "17")

-- combat-rocket
util.regroup.setSubgroupToPrototype("rocket-item-rampant-arsenal", "combat-rocket", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-rocket-item-rampant-arsenal", "combat-rocket", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-rocket-item-rampant-arsenal", "combat-rocket", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-rocket-item-rampant-arsenal", "combat-rocket", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-rocket-item-rampant-arsenal", "combat-rocket", "05")
util.regroup.setSubgroupToPrototype("rapid-rocket-item-rampant-arsenal", "combat-rocket", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "10")
util.regroup.setSubgroupToPrototype("rocket-launcher", "combat-rocket", "11")
util.regroup.setSubgroupToPrototype("rocket-launcher-gun-rampant-arsenal", "combat-rocket", "12")
util.regroup.setSubgroupToPrototype("heavy-rocket-launcher", "combat-rocket", "13")
util.regroup.setSubgroupToPrototype("rocket", "combat-rocket", "14")
util.regroup.setSubgroupToPrototype("explosive-rocket", "combat-rocket", "15")
util.regroup.setSubgroupToPrototype("se-plague-bomb", "combat-rocket", "16")
util.regroup.setSubgroupToPrototype("heavy-rocket", "combat-rocket", "17")
util.regroup.setSubgroupToPrototype("atomic-bomb", "combat-rocket", "18")
util.regroup.setSubgroupToPrototype("fi_atomic_bomb_recipe", "combat-rocket", "19")
util.regroup.setSubgroupToPrototype("antimatter-rocket", "combat-rocket", "20")
util.regroup.setSubgroupToPrototype("bio-rocket-ammo-rampant-arsenal", "combat-rocket", "21")
util.regroup.setSubgroupToPrototype("he-rocket-ammo-rampant-arsenal", "combat-rocket", "22")
util.regroup.setSubgroupToPrototype("incendiary-rocket-ammo-rampant-arsenal", "combat-rocket", "23")

-- combat-railgun
util.regroup.setSubgroupToPrototype("kr-railgun-turret", "combat-railgun", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-kr-railgun-turret", "combat-railgun", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-kr-railgun-turret", "combat-railgun", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-kr-railgun-turret", "combat-railgun", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-kr-railgun-turret", "combat-railgun", "05")
util.regroup.setSubgroupToPrototype("basic-railgun-shell", "combat-railgun", "06")
util.regroup.setSubgroupToPrototype("explosion-railgun-shell", "combat-railgun", "07")
util.regroup.setSubgroupToPrototype("antimatter-railgun-shell", "combat-railgun", "08")

-- combat-rocket-turret
util.regroup.setSubgroupToPrototype("kr-rocket-turret", "combat-rocket-turret", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-kr-rocket-turret", "combat-rocket-turret", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-kr-rocket-turret", "combat-rocket-turret", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-kr-rocket-turret", "combat-rocket-turret", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-kr-rocket-turret", "combat-rocket-turret", "05")
util.regroup.setSubgroupToPrototype("explosive-turret-rocket", "combat-rocket-turret", "06")
util.regroup.setSubgroupToPrototype("nuclear-turret-rocket", "combat-rocket-turret", "07")
util.regroup.setSubgroupToPrototype("antimatter-turret-rocket", "combat-rocket-turret", "08")

-- combat-laser
util.regroup.setSubgroupToPrototype("laser-turret", "combat-laser", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-laser-turret", "combat-laser", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-laser-turret", "combat-laser", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-laser-turret", "combat-laser", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-laser-turret", "combat-laser", "05")
util.regroup.setSubgroupToPrototype("lightning-item-rampant-arsenal", "combat-laser", "06")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-lightning-item-rampant-arsenal", "combat-laser", "07")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-lightning-item-rampant-arsenal", "combat-laser", "08")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-lightning-item-rampant-arsenal", "combat-laser", "09")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-lightning-item-rampant-arsenal", "combat-laser", "10")
util.regroup.setSubgroupToPrototype("advanced-beam-item-rampant-arsenal", "combat-laser", "11")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-advanced-beam-item-rampant-arsenal", "combat-laser", "12")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-advanced-beam-item-rampant-arsenal", "combat-laser", "13")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-advanced-beam-item-rampant-arsenal", "combat-laser", "14")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-advanced-beam-item-rampant-arsenal", "combat-laser", "15")
util.regroup.setSubgroupToPrototype("advanced-laser-item-rampant-arsenal", "combat-laser", "16")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-advanced-laser-item-rampant-arsenal", "combat-laser", "17")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-advanced-laser-item-rampant-arsenal", "combat-laser", "18")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-advanced-laser-item-rampant-arsenal", "combat-laser", "19")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-advanced-laser-item-rampant-arsenal", "combat-laser", "20")
util.regroup.setSubgroupToPrototype("kr-laser-artillery-turret", "combat-laser", "21")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-kr-laser-artillery-turret", "combat-laser", "22")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-kr-laser-artillery-turret", "combat-laser", "23")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-kr-laser-artillery-turret", "combat-laser", "24")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-kr-laser-artillery-turret", "combat-laser", "25")

-- combat-artillery
util.regroup.setSubgroupToPrototype("artillery-turret", "combat-artillery", "01")
util.regroup.setSubgroupToPrototype("hero-turret-1-for-artillery-turret", "combat-artillery", "02")
util.regroup.setSubgroupToPrototype("hero-turret-2-for-artillery-turret", "combat-artillery", "03")
util.regroup.setSubgroupToPrototype("hero-turret-3-for-artillery-turret", "combat-artillery", "04")
util.regroup.setSubgroupToPrototype("hero-turret-4-for-artillery-turret", "combat-artillery", "05")
util.regroup.setSubgroupToPrototype("artillery-shell", "combat-artillery", "06")
util.regroup.setSubgroupToPrototype("nuclear-artillery-shell", "combat-artillery", "07")
util.regroup.setSubgroupToPrototype("antimatter-artillery-shell", "combat-artillery", "08")
util.regroup.setSubgroupToPrototype("bio-artillery-ammo-rampant-arsenal", "combat-artillery", "09")
util.regroup.setSubgroupToPrototype("he-artillery-ammo-rampant-arsenal", "combat-artillery", "10")
util.regroup.setSubgroupToPrototype("incendiary-artillery-ammo-rampant-arsenal", "combat-artillery", "11")
util.regroup.setSubgroupToPrototype("nuclear-artillery-ammo-rampant-arsenal", "combat-artillery", "12")

-- combat-surface-defense
util.regroup.setSubgroupToPrototype("se-meteor-point-defence", "combat-surface-defense", "01")
util.regroup.setSubgroupToPrototype("se-meteor-point-defence-ammo", "combat-surface-defense", "02")
util.regroup.setSubgroupToPrototype("se-meteor-defence", "combat-surface-defense", "03")
util.regroup.setSubgroupToPrototype("se-meteor-defence-ammo", "combat-surface-defense", "04")
util.regroup.setSubgroupToPrototype("se-energy-beam-defence", "combat-surface-defense", "05")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-weapon", "combat-surface-defense", "06")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-weapon-capsule", "combat-surface-defense", "07")

-- combat-grenade
util.regroup.setSubgroupToPrototype("grenade", "combat-grenade", "01")
util.regroup.setSubgroupToPrototype("cluster-grenade", "combat-grenade", "02")
util.regroup.setSubgroupToPrototype("el_grenade", "combat-grenade", "03")
util.regroup.setSubgroupToPrototype("el_grenade_recipe", "combat-grenade", "04")
util.regroup.setSubgroupToPrototype("fi_grenade", "combat-grenade", "05")
util.regroup.setSubgroupToPrototype("fi_grenade_recipe", "combat-grenade", "06")
util.regroup.setSubgroupToPrototype("fu_grenade", "combat-grenade", "07")
util.regroup.setSubgroupToPrototype("fu_grenade_recipe", "combat-grenade", "08")
util.regroup.setSubgroupToPrototype("bio-grenade-capsule-rampant-arsenal", "combat-grenade", "09")
util.regroup.setSubgroupToPrototype("he-grenade-capsule-rampant-arsenal", "combat-grenade", "10")
util.regroup.setSubgroupToPrototype("incendiary-grenade-capsule-rampant-arsenal", "combat-grenade", "11")
util.regroup.setSubgroupToPrototype("poison-capsule", "combat-grenade", "12")
util.regroup.setSubgroupToPrototype("toxic-capsule-rampant-arsenal", "combat-grenade", "13")
util.regroup.setSubgroupToPrototype("paralysis-capsule-rampant-arsenal", "combat-grenade", "14")
util.regroup.setSubgroupToPrototype("repair-capsule-rampant-arsenal", "combat-grenade", "15")
util.regroup.setSubgroupToPrototype("healing-capsule-rampant-arsenal", "combat-grenade", "16")
util.regroup.setSubgroupToPrototype("slowdown-capsule", "combat-grenade", "17")
util.regroup.setSubgroupToPrototype("speed-capsule-rampant-arsenal", "combat-grenade", "18")
util.regroup.setSubgroupToPrototype("kr-biter-virus", "combat-grenade", "19")
util.regroup.setSubgroupToPrototype("kr-creep-virus", "combat-grenade", "20")
util.regroup.setSubgroupToPrototype("cliff-explosives", "combat-grenade", "21")
util.regroup.setSubgroupToPrototype("defender-capsule", "combat-grenade", "22")
util.regroup.setSubgroupToPrototype("distractor-capsule", "combat-grenade", "23")
util.regroup.setSubgroupToPrototype("destroyer-capsule", "combat-grenade", "24")

-- combat-biter-capsule
util.regroup.setSubgroupToPrototype("se-capsule-small-biter", "combat-biter-capsule", "01")
util.regroup.setSubgroupToPrototype("se-capsule-medium-biter", "combat-biter-capsule", "02")
util.regroup.setSubgroupToPrototype("se-capsule-big-biter", "combat-biter-capsule", "03")
util.regroup.setSubgroupToPrototype("se-capsule-behemoth-biter", "combat-biter-capsule", "04")
util.regroup.setSubgroupToPrototype("se-capsule-small-spitter", "combat-biter-capsule", "05")
util.regroup.setSubgroupToPrototype("se-capsule-medium-spitter", "combat-biter-capsule", "06")
util.regroup.setSubgroupToPrototype("se-capsule-big-spitter", "combat-biter-capsule", "07")
util.regroup.setSubgroupToPrototype("se-capsule-behemoth-spitter", "combat-biter-capsule", "08")
