local util = require("functions/util")

util.regroup.createSubgroup("intermediate-product-magazine", "intermediate-products", "raw-01")
util.regroup.createSubgroup("intermediate-product", "intermediate-products", "raw-02")
util.regroup.createSubgroup("intermediate-product-nuclear-cell", "intermediate-products", "raw-03")
util.regroup.createSubgroup("intermediate-product-other-cell", "intermediate-products", "raw-04")
util.regroup.createSubgroup("intermediate-product-cable", "intermediate-products", "raw-05")
util.regroup.createSubgroup("intermediate-product-battery", "intermediate-products", "raw-06")
util.regroup.createSubgroup("intermediate-product-gear-wheel", "intermediate-products", "raw-07")
util.regroup.createSubgroup("intermediate-product-frame-components", "intermediate-products", "raw-08")
util.regroup.createSubgroup("intermediate-product-gearbox", "intermediate-products", "raw-09")
util.regroup.createSubgroup("intermediate-product-articulated", "intermediate-products", "raw-10")
util.regroup.createSubgroup("intermediate-product-flow-contol", "intermediate-products", "raw-11")
util.regroup.createSubgroup("intermediate-product-rotary-components", "intermediate-products", "raw-12")
util.regroup.createSubgroup("intermediate-product-engine-components", "intermediate-products", "raw-13")
util.regroup.createSubgroup("intermediate-product-electronic", "intermediate-products", "raw-14")
util.regroup.createSubgroup("intermediate-product-electronic-components", "intermediate-products", "raw-15")
util.regroup.createSubgroup("intermediate-product-processor", "intermediate-products", "raw-16")
util.regroup.createSubgroup("intermediate-product-rocket-part", "intermediate-products", "raw-17")
util.regroup.createSubgroup("intermediate-product-intersurface-part", "intermediate-products", "raw-18")
util.regroup.createSubgroup("intermediate-product-canister", "intermediate-products", "raw-19")
util.regroup.createSubgroup("intermediate-product-recycling", "intermediate-products", "raw-20")

-- intermediate-product-magazine
util.regroup.setSubgroupToPrototype("empty-shotgun-recipe", "intermediate-product-magazine", "01")
util.regroup.setSubgroupToPrototype("empty-shotgun-shell", "intermediate-product-magazine", "02")
util.regroup.setSubgroupToPrototype("empty-high-capacity-shotgun-recipe", "intermediate-product-magazine", "03")
util.regroup.setSubgroupToPrototype("empty-high-capacity-shotgun-shell", "intermediate-product-magazine", "04")
util.regroup.setSubgroupToPrototype("empty-recipe", "intermediate-product-magazine", "05")
util.regroup.setSubgroupToPrototype("empty-magazine", "intermediate-product-magazine", "06")
util.regroup.setSubgroupToPrototype("empty-high-capacity-recipe", "intermediate-product-magazine", "07")
util.regroup.setSubgroupToPrototype("advanced-recipe", "intermediate-product-magazine", "08")
util.regroup.setSubgroupToPrototype("advanced-high-capacity-recipe", "intermediate-product-magazine", "09")

-- intermediate-product
util.regroup.setSubgroupToPrototype("fi_modules_base_item", "intermediate-product", "01")
util.regroup.setSubgroupToPrototype("fi_modules_base_recipe", "intermediate-product", "02")
util.regroup.setSubgroupToPrototype("fi_modules_core_item", "intermediate-product", "03")
util.regroup.setSubgroupToPrototype("fi_modules_core_recipe", "intermediate-product", "04")
util.regroup.setSubgroupToPrototype("automation-core", "intermediate-product", "05")
util.regroup.setSubgroupToPrototype("ai-core", "intermediate-product", "05")
util.regroup.setSubgroupToPrototype("fu_miner_fuel_item", "intermediate-product", "06")
util.regroup.setSubgroupToPrototype("fu_drill_recipe", "intermediate-product", "07")
util.regroup.setSubgroupToPrototype("flying-robot-frame", "intermediate-product", "08")
util.regroup.setSubgroupToPrototype("fi_materials_upgrade", "intermediate-product", "09")
util.regroup.setSubgroupToPrototype("fi_upgrade_recipe", "intermediate-product", "10")
util.regroup.setSubgroupToPrototype("fu_materials_upgrade", "intermediate-product", "11")
util.regroup.setSubgroupToPrototype("fu_upgrade_recipe", "intermediate-product", "12")
util.regroup.setSubgroupToPrototype("gr_materials_upgrade", "intermediate-product", "13")
util.regroup.setSubgroupToPrototype("gr_upgrade_recipe", "intermediate-product", "14")
util.regroup.setSubgroupToPrototype("gr_materials_stack_up_item_recipe", "intermediate-product", "15")
util.regroup.setSubgroupToPrototype("gr_materials_stack_up_item", "intermediate-product", "16")
util.regroup.setSubgroupToPrototype("gr_materials_stack_down_item_recipe", "intermediate-product", "17")
util.regroup.setSubgroupToPrototype("gr_materials_stack_down_item", "intermediate-product", "18")

-- intermediate-product-nuclear-cell
util.regroup.setSubgroupToPrototype("uranium-fuel-cell", "intermediate-product-nuclear-cell", "01")
util.regroup.setSubgroupToPrototype("fi_basic_fuel_item", "intermediate-product-nuclear-cell", "02")
util.regroup.setSubgroupToPrototype("fi_basic_fuel_recipe", "intermediate-product-nuclear-cell", "03")
util.regroup.setSubgroupToPrototype("fi_basic_thorium_fuel_item", "intermediate-product-nuclear-cell", "04")
util.regroup.setSubgroupToPrototype("fi_basic_thorium_fuel_recipe", "intermediate-product-nuclear-cell", "05")
util.regroup.setSubgroupToPrototype("fi_advanced_fuel_item", "intermediate-product-nuclear-cell", "06")
util.regroup.setSubgroupToPrototype("fi_advanced_fuel_recipe", "intermediate-product-nuclear-cell", "07")
util.regroup.setSubgroupToPrototype("fi_advanced_thorium_fuel_item", "intermediate-product-nuclear-cell", "08")
util.regroup.setSubgroupToPrototype("fi_advanced_thorium_fuel_recipe", "intermediate-product-nuclear-cell", "09")
util.regroup.setSubgroupToPrototype("fi_pure_fuel_item", "intermediate-product-nuclear-cell", "10")
util.regroup.setSubgroupToPrototype("fi_pure_fuel_recipe", "intermediate-product-nuclear-cell", "11")
util.regroup.setSubgroupToPrototype("used-up-uranium-fuel-cell", "intermediate-product-nuclear-cell", "12")
util.regroup.setSubgroupToPrototype("fi_used_basic_fuel_item", "intermediate-product-nuclear-cell", "13")
util.regroup.setSubgroupToPrototype("fi_used_basic_thorium_fuel_item", "intermediate-product-nuclear-cell", "14")
util.regroup.setSubgroupToPrototype("fi_used__basic_thorium_fuel_recipe", "intermediate-product-nuclear-cell", "15")
util.regroup.setSubgroupToPrototype("fi_used_advanced_fuel_item", "intermediate-product-nuclear-cell", "16")
util.regroup.setSubgroupToPrototype("fi_used_advanced_fuel_recipe", "intermediate-product-nuclear-cell", "17")
util.regroup.setSubgroupToPrototype("fi_used_advanced_thorium_fuel_item", "intermediate-product-nuclear-cell", "18")
util.regroup.setSubgroupToPrototype("fi_used_advanced_thorium_fuel_recipe", "intermediate-product-nuclear-cell", "19")
util.regroup.setSubgroupToPrototype("fi_used_pure_fuel_item", "intermediate-product-nuclear-cell", "20")
util.regroup.setSubgroupToPrototype("fi_used_pure_fuel_recipe", "intermediate-product-nuclear-cell", "21")
util.regroup.setSubgroupToPrototype("fi_materials_waste", "intermediate-product-nuclear-cell", "22")
util.regroup.setSubgroupToPrototype("fi_decay_waste_recipe", "intermediate-product-nuclear-cell", "23")

-- intermediate-product-other-cell
util.regroup.setSubgroupToPrototype("empty-dt-fuel", "intermediate-product-other-cell", "01")
util.regroup.setSubgroupToPrototype("dt-fuel", "intermediate-product-other-cell", "02")
util.regroup.setSubgroupToPrototype("se-kr-basic-stabilizer", "intermediate-product-other-cell", "03")
util.regroup.setSubgroupToPrototype("se-kr-charge-basic-stabilizer", "intermediate-product-other-cell", "04")
util.regroup.setSubgroupToPrototype("se-kr-charged-basic-stabilizer", "intermediate-product-other-cell", "05")
util.regroup.setSubgroupToPrototype("matter-stabilizer", "intermediate-product-other-cell", "06")
util.regroup.setSubgroupToPrototype("charge-stabilizer", "intermediate-product-other-cell", "07")
util.regroup.setSubgroupToPrototype("charged-matter-stabilizer", "intermediate-product-other-cell", "08")
util.regroup.setSubgroupToPrototype("empty-antimatter-fuel-cell", "intermediate-product-other-cell", "09")
util.regroup.setSubgroupToPrototype("charged-antimatter-fuel-cell", "intermediate-product-other-cell", "10")
util.regroup.setSubgroupToPrototype("fu_materials_empty_container", "intermediate-product-other-cell", "11")
util.regroup.setSubgroupToPrototype("fu_empty_container_recipe", "intermediate-product-other-cell", "12")
util.regroup.setSubgroupToPrototype("fu_materials_charged_container", "intermediate-product-other-cell", "13")
util.regroup.setSubgroupToPrototype("fu_stelerator_2_neutron_recipe", "intermediate-product-other-cell", "14")
util.regroup.setSubgroupToPrototype("fu_stelerator_3_neutron_recipe", "intermediate-product-other-cell", "15")
util.regroup.setSubgroupToPrototype("gr_materials_fusion_cell_recipe", "intermediate-product-other-cell", "16")
util.regroup.setSubgroupToPrototype("gr_materials_fusion_cell_item", "intermediate-product-other-cell", "17")
util.regroup.setSubgroupToPrototype("space-train-battery-pack", "intermediate-product-other-cell", "18")
util.regroup.setSubgroupToPrototype("pollution-filter", "intermediate-product-other-cell", "19")
util.regroup.setSubgroupToPrototype("restore-used-pollution-filter", "intermediate-product-other-cell", "20")
util.regroup.setSubgroupToPrototype("improved-pollution-filter", "intermediate-product-other-cell", "21")
util.regroup.setSubgroupToPrototype("restore-used-improved-pollution-filter", "intermediate-product-other-cell", "22")

-- intermediate-product-cable
util.regroup.setSubgroupToPrototype("copper-cable", "intermediate-product-cable", "01")
util.regroup.setSubgroupToPrototype("aluminum-cable", "intermediate-product-cable", "02")
util.regroup.setSubgroupToPrototype("silver-wire", "intermediate-product-cable", "03")
util.regroup.setSubgroupToPrototype("tinned-cable", "intermediate-product-cable", "04")
util.regroup.setSubgroupToPrototype("optical-fiber", "intermediate-product-cable", "05")
util.regroup.setSubgroupToPrototype("acsr-cable", "intermediate-product-cable", "06")
util.regroup.setSubgroupToPrototype("gr_gold_wire_recipe", "intermediate-product-cable", "07")
util.regroup.setSubgroupToPrototype("gr_materials_gold_wire", "intermediate-product-cable", "08")
util.regroup.setSubgroupToPrototype("se-holmium-cable", "intermediate-product-cable", "09")
util.regroup.setSubgroupToPrototype("se-superconductive-cable", "intermediate-product-cable", "10")

-- intermediate-product-battery
util.regroup.setSubgroupToPrototype("battery", "intermediate-product-battery", "01")
util.regroup.setSubgroupToPrototype("el_lithium_basic_battery_recipe", "intermediate-product-battery", "012")
util.regroup.setSubgroupToPrototype("el_lithium_battery", "intermediate-product-battery", "02")
util.regroup.setSubgroupToPrototype("el_lithium_battery_recipe", "intermediate-product-battery", "02")
util.regroup.setSubgroupToPrototype("solar-cell", "intermediate-product-battery", "03")
util.regroup.setSubgroupToPrototype("lithium-sulfur-battery", "intermediate-product-battery", "04")

-- intermediate-product-gear-wheel
util.regroup.setSubgroupToPrototype("iron-gear-wheel", "intermediate-product-gear-wheel", "01")
util.regroup.setSubgroupToPrototype("steel-gear-wheel", "intermediate-product-gear-wheel", "02")
util.regroup.setSubgroupToPrototype("imersium-gear-wheel", "intermediate-product-gear-wheel", "03")

-- intermediate-product-frame-components
util.regroup.setSubgroupToPrototype("iron-stick", "intermediate-product-frame-components", "01")
util.regroup.setSubgroupToPrototype("iron-beam", "intermediate-product-frame-components", "02")
util.regroup.setSubgroupToPrototype("steel-beam", "intermediate-product-frame-components", "03")
util.regroup.setSubgroupToPrototype("galvanized-steel-plate", "intermediate-product-frame-components", "04")
util.regroup.setSubgroupToPrototype("imersium-beam", "intermediate-product-frame-components", "05")
util.regroup.setSubgroupToPrototype("hardened-hull", "intermediate-product-frame-components", "06")
util.regroup.setSubgroupToPrototype("hardened-hull-iridium", "intermediate-product-frame-components", "07")
util.regroup.setSubgroupToPrototype("nitinol-mesh", "intermediate-product-frame-components", "08")
util.regroup.setSubgroupToPrototype("nitinol-mesh-beryllium", "intermediate-product-frame-components", "09")
util.regroup.setSubgroupToPrototype("se-heavy-girder", "intermediate-product-frame-components", "10")
util.regroup.setSubgroupToPrototype("se-heavy-composite", "intermediate-product-frame-components", "11")
util.regroup.setSubgroupToPrototype("se-aeroframe-pole", "intermediate-product-frame-components", "12")
util.regroup.setSubgroupToPrototype("se-aeroframe-scaffold", "intermediate-product-frame-components", "13")
util.regroup.setSubgroupToPrototype("se-aeroframe-scaffold-nanotubes", "intermediate-product-frame-components", "14")
util.regroup.setSubgroupToPrototype("se-aeroframe-bulkhead", "intermediate-product-frame-components", "15")
util.regroup.setSubgroupToPrototype("se-nanomaterial", "intermediate-product-frame-components", "16")
util.regroup.setSubgroupToPrototype("se-nanomaterial-nanotubes", "intermediate-product-frame-components", "17")

-- intermediate-product-gearbox
util.regroup.setSubgroupToPrototype("gearbox", "intermediate-product-gearbox", "01")
util.regroup.setSubgroupToPrototype("gearbox-iridium", "intermediate-product-gearbox", "02")
util.regroup.setSubgroupToPrototype("advanced-gearbox", "intermediate-product-gearbox", "03")
util.regroup.setSubgroupToPrototype("elite-gearbox", "intermediate-product-gearbox", "04")
util.regroup.setSubgroupToPrototype("se-heavy-assembly", "intermediate-product-gearbox", "05")

-- intermediate-product-articulated
util.regroup.setSubgroupToPrototype("articulated-mechanism", "intermediate-product-articulated", "01")
util.regroup.setSubgroupToPrototype("motorized-articulator", "intermediate-product-articulated", "02")
util.regroup.setSubgroupToPrototype("complex-joint", "intermediate-product-articulated", "03")
util.regroup.setSubgroupToPrototype("complex-joint-iridium", "intermediate-product-articulated", "04")
util.regroup.setSubgroupToPrototype("inserter-parts", "intermediate-product-articulated", "05")
util.regroup.setSubgroupToPrototype("machining-tool", "intermediate-product-articulated", "06")
util.regroup.setSubgroupToPrototype("advanced-machining-tool", "intermediate-product-articulated", "07")
util.regroup.setSubgroupToPrototype("industrial-drill-head", "intermediate-product-articulated", "07")

-- intermediate-product-flow-contol
util.regroup.setSubgroupToPrototype("invar-valve", "intermediate-product-flow-contol", "01")
util.regroup.setSubgroupToPrototype("flow-controller", "intermediate-product-flow-contol", "02")
util.regroup.setSubgroupToPrototype("flow-controller-biological", "intermediate-product-flow-contol", "03")
util.regroup.setSubgroupToPrototype("advanced-flow-controller", "intermediate-product-flow-contol", "04")
util.regroup.setSubgroupToPrototype("advanced-flow-controller-biological", "intermediate-product-flow-contol", "05")
util.regroup.setSubgroupToPrototype("self-regulating-valve", "intermediate-product-flow-contol", "06")
util.regroup.setSubgroupToPrototype("se-bioscrubber", "intermediate-product-flow-contol", "07")
util.regroup.setSubgroupToPrototype("se-lattice-pressure-vessel", "intermediate-product-flow-contol", "08")

-- intermediate-product-rotary-components
util.regroup.setSubgroupToPrototype("bolted-flange", "intermediate-product-rotary-components", "01")
util.regroup.setSubgroupToPrototype("flywheel", "intermediate-product-rotary-components", "02")
util.regroup.setSubgroupToPrototype("airtight-seal", "intermediate-product-rotary-components", "03")
util.regroup.setSubgroupToPrototype("airtight-seal-vitalic", "intermediate-product-rotary-components", "04")
util.regroup.setSubgroupToPrototype("brass-balls", "intermediate-product-rotary-components", "05")
util.regroup.setSubgroupToPrototype("bearing", "intermediate-product-rotary-components", "06")
util.regroup.setSubgroupToPrototype("titanium-palladium-flange", "intermediate-product-rotary-components", "07")
util.regroup.setSubgroupToPrototype("cooling-fan", "intermediate-product-rotary-components", "08")
util.regroup.setSubgroupToPrototype("gyroscope", "intermediate-product-rotary-components", "09")
util.regroup.setSubgroupToPrototype("se-heavy-bearing", "intermediate-product-rotary-components", "10")

-- intermediate-product-engine-components
util.regroup.setSubgroupToPrototype("motor", "intermediate-product-engine-components", "01")
util.regroup.setSubgroupToPrototype("electric-motor", "intermediate-product-engine-components", "02")
util.regroup.setSubgroupToPrototype("electric-motor-silver", "intermediate-product-engine-components", "03")
util.regroup.setSubgroupToPrototype("spark-plug", "intermediate-product-engine-components", "04")
util.regroup.setSubgroupToPrototype("engine-unit", "intermediate-product-engine-components", "05")
util.regroup.setSubgroupToPrototype("electric-engine-unit", "intermediate-product-engine-components", "06")

-- intermediate-product-electronic
util.regroup.setSubgroupToPrototype("nickel-electromagnet", "intermediate-product-electronic", "01")
util.regroup.setSubgroupToPrototype("energy-control-unit", "intermediate-product-electronic", "02")
util.regroup.setSubgroupToPrototype("se-holmium-solenoid", "intermediate-product-electronic", "03")
util.regroup.setSubgroupToPrototype("se-dynamic-emitter", "intermediate-product-electronic", "04")
util.regroup.setSubgroupToPrototype("fu_magnet_1_recipe", "intermediate-product-electronic", "05")
util.regroup.setSubgroupToPrototype("fu_materials_magnet", "intermediate-product-electronic", "06")
util.regroup.setSubgroupToPrototype("gr_plasma_cube_recipe", "intermediate-product-electronic", "07")
util.regroup.setSubgroupToPrototype("gr_materials_plasma_cube", "intermediate-product-electronic", "08")
util.regroup.setSubgroupToPrototype("gr_magnet_recipe", "intermediate-product-electronic", "09")
util.regroup.setSubgroupToPrototype("gr_materials_magnet", "intermediate-product-electronic", "10")

-- intermediate-product-electronic-components
util.regroup.setSubgroupToPrototype("electronic-components", "intermediate-product-electronic-components", "01")
util.regroup.setSubgroupToPrototype("electronic-components-lithium", "intermediate-product-electronic-components", "02")
util.regroup.setSubgroupToPrototype("solder", "intermediate-product-electronic-components", "03")
util.regroup.setSubgroupToPrototype("pcb-solder", "intermediate-product-electronic-components", "04")
util.regroup.setSubgroupToPrototype("insulated-cable", "intermediate-product-electronic-components", "05")
util.regroup.setSubgroupToPrototype("basic-electronic-components", "intermediate-product-electronic-components", "06")
util.regroup.setSubgroupToPrototype("BOBMD-electronic-components", "intermediate-product-electronic-components", "07")
util.regroup.setSubgroupToPrototype("intergrated-electronics", "intermediate-product-electronic-components", "08")
util.regroup.setSubgroupToPrototype("processing-electronics", "intermediate-product-electronic-components", "09")
util.regroup.setSubgroupToPrototype("phenolic-board", "intermediate-product-electronic-components", "10")
util.regroup.setSubgroupToPrototype("phenolic-board-stone", "intermediate-product-electronic-components", "11")
util.regroup.setSubgroupToPrototype("fibreglass-board", "intermediate-product-electronic-components", "12")
util.regroup.setSubgroupToPrototype("basic-circuit-board", "intermediate-product-electronic-components", "13")
util.regroup.setSubgroupToPrototype("circuit-board", "intermediate-product-electronic-components", "14")
util.regroup.setSubgroupToPrototype("superior-circuit-board", "intermediate-product-electronic-components", "15")
util.regroup.setSubgroupToPrototype("multi-layer-circuit-board", "intermediate-product-electronic-components", "16")
util.regroup.setSubgroupToPrototype("pcb-substrate", "intermediate-product-electronic-components", "17")
util.regroup.setSubgroupToPrototype("gr_pcb_recipe", "intermediate-product-electronic-components", "18")
util.regroup.setSubgroupToPrototype("gr_materials_pcb", "intermediate-product-electronic-components", "19")
util.regroup.setSubgroupToPrototype("mainboard", "intermediate-product-electronic-components", "20")
util.regroup.setSubgroupToPrototype("mainboard-holmium", "intermediate-product-electronic-components", "21")
util.regroup.setSubgroupToPrototype("mlcc", "intermediate-product-electronic-components", "22")
util.regroup.setSubgroupToPrototype("temperature-sensor", "intermediate-product-electronic-components", "23")
util.regroup.setSubgroupToPrototype("cpu", "intermediate-product-electronic-components", "24")
util.regroup.setSubgroupToPrototype("cpu-holmium", "intermediate-product-electronic-components", "25")

-- intermediate-product-processor
util.regroup.setSubgroupToPrototype("electronic-circuit", "intermediate-product-processor", "01")
util.regroup.setSubgroupToPrototype("electronic-circuit-silver", "intermediate-product-processor", "02")
util.regroup.setSubgroupToPrototype("advanced-circuit", "intermediate-product-processor", "03")
util.regroup.setSubgroupToPrototype("processing-unit", "intermediate-product-processor", "04")
util.regroup.setSubgroupToPrototype("advanced-processing-unit", "intermediate-product-processor", "05")
util.regroup.setSubgroupToPrototype("se-quantum-processor", "intermediate-product-processor", "06")
util.regroup.setSubgroupToPrototype("se-naquium-processor", "intermediate-product-processor", "07")
util.regroup.setSubgroupToPrototype("se-naquium-processor-alt", "intermediate-product-processor", "08")
util.regroup.setSubgroupToPrototype("gr_circuit_recipe", "intermediate-product-processor", "09")
util.regroup.setSubgroupToPrototype("gr_materials_circuit", "intermediate-product-processor", "10")

-- intermediate-product-rocket-part
util.regroup.setSubgroupToPrototype("low-density-structure", "intermediate-product-rocket-part", "01")
util.regroup.setSubgroupToPrototype("low-density-structure", "intermediate-product-rocket-part", "02")
util.regroup.setSubgroupToPrototype("low-density-structure-nanotubes", "intermediate-product-rocket-part", "03")
util.regroup.setSubgroupToPrototype("se-low-density-structure-beryllium", "intermediate-product-rocket-part", "04")
util.regroup.setSubgroupToPrototype("fi_low-density-structure_recipe", "intermediate-product-rocket-part", "05")
util.regroup.setSubgroupToPrototype("rocket-control-unit", "intermediate-product-rocket-part", "06")
util.regroup.setSubgroupToPrototype("rocket-engine-nozzle", "intermediate-product-rocket-part", "07")
util.regroup.setSubgroupToPrototype("gimbaled-thruster", "intermediate-product-rocket-part", "08")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-cargo-pod", "intermediate-product-rocket-part", "09")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-fuel-tank", "intermediate-product-rocket-part", "10")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-section", "intermediate-product-rocket-part", "11")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-section-beryllium", "intermediate-product-rocket-part", "12")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-section-unpack", "intermediate-product-rocket-part", "13")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-section-pack", "intermediate-product-rocket-part", "14")
util.regroup.setSubgroupToPrototype("se-cargo-rocket-section-packed", "intermediate-product-rocket-part", "15")

-- intermediate-product-intersurface-part
util.regroup.setSubgroupToPrototype("skyseeker-armature", "intermediate-product-intersurface-part", "01")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-capsule", "intermediate-product-intersurface-part", "02")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-capsule-iridium", "intermediate-product-intersurface-part", "03")
util.regroup.setSubgroupToPrototype("se-space-elevator-cable", "intermediate-product-intersurface-part", "04")
util.regroup.setSubgroupToPrototype("se-space-elevator-cable-nano", "intermediate-product-intersurface-part", "05")

-- intermediate-product-canister
util.regroup.setSubgroupToPrototype("empty-barrel", "intermediate-product-canister", "01")

-- intermediate-product-recycling
util.regroup.setSubgroupToPrototype("se-recycle-small-iron-electric-pole", "intermediate-product-recycling", "01")
util.regroup.setSubgroupToPrototype("se-recycle-small-electric-pole", "intermediate-product-recycling", "02")
util.regroup.setSubgroupToPrototype("se-recycle-medium-electric-pole", "intermediate-product-recycling", "03")
util.regroup.setSubgroupToPrototype("se-recycle-big-electric-pole", "intermediate-product-recycling", "04")
util.regroup.setSubgroupToPrototype("se-recycle-substation", "intermediate-product-recycling", "05")
util.regroup.setSubgroupToPrototype("se-recycle-radar", "intermediate-product-recycling", "06")
util.regroup.setSubgroupToPrototype("se-empty-barrel-reprocessing", "intermediate-product-recycling", "07")
util.regroup.setSubgroupToPrototype("se-scrap-decontamination", "intermediate-product-recycling", "08")
util.regroup.setSubgroupToPrototype("se-scrap-recycling", "intermediate-product-recycling", "09")
util.regroup.setSubgroupToPrototype("se-broken-data-scrapping", "intermediate-product-recycling", "10")
util.regroup.setSubgroupToPrototype("se-cargo-pod-scrapping", "intermediate-product-recycling", "11")
util.regroup.setSubgroupToPrototype("se-space-capsule-scorched-scrapping", "intermediate-product-recycling", "12")
util.regroup.setSubgroupToPrototype("se-space-capsule-scrapping", "intermediate-product-recycling", "13")
util.regroup.setSubgroupToPrototype("space-train-battery-pack-refurbish", "intermediate-product-recycling", "14")
