local util = require("functions/util")

util.regroup.createSubgroup("logistic-container-1", "logistics", "raw-01")
util.regroup.createSubgroup("logistic-container-2", "logistics", "raw-02")
util.regroup.createSubgroup("logistic-container-4", "logistics", "raw-03")
util.regroup.createSubgroup("logistic-container-6", "logistics", "raw-04")
util.regroup.createSubgroup("logistic-storage", "logistics", "raw-05")
util.regroup.createSubgroup("logistic-belt", "logistics", "raw-06")
util.regroup.createSubgroup("logistic-transport-belt", "logistics", "raw-07")
util.regroup.createSubgroup("logistic-underground-belt", "logistics", "raw-08")
util.regroup.createSubgroup("logistic-splitter", "logistics", "raw-09")
util.regroup.createSubgroup("logistic-inserter", "logistics", "raw-10")
util.regroup.createSubgroup("logistic-cranes", "logistics", "raw-11")
util.regroup.createSubgroup("logistic-pole-middle", "logistics", "raw-12")
util.regroup.createSubgroup("logistic-pole-big", "logistics", "raw-13")
util.regroup.createSubgroup("logistic-pole-substation", "logistics", "raw-14")
util.regroup.createSubgroup("logistic-drones", "logistics", "raw-15")
util.regroup.createSubgroup("logistic-network", "logistics", "raw-16")
util.regroup.createSubgroup("logistic-circuit-network", "logistics", "raw-17")
util.regroup.createSubgroup("logistic-rocket", "logistics", "raw-18")

-- logistic-container-1
util.regroup.setSubgroupToPrototype("steel-chest", "logistic-container-1", "01")
util.regroup.setSubgroupToPrototype("logistic-chest-passive-provider", "logistic-container-1", "02")
util.regroup.setSubgroupToPrototype("logistic-chest-active-provider", "logistic-container-1", "03")
util.regroup.setSubgroupToPrototype("logistic-chest-storage", "logistic-container-1", "04")
util.regroup.setSubgroupToPrototype("logistic-chest-buffer", "logistic-container-1", "05")
util.regroup.setSubgroupToPrototype("logistic-chest-requester", "logistic-container-1", "06")
util.regroup.setSubgroupToPrototype("iron-chest", "logistic-container-1", "07")
util.regroup.setSubgroupToPrototype("wooden-chest", "logistic-container-1", "08")

-- logistic-container-2
util.regroup.setSubgroupToPrototype("aai-strongbox", "logistic-container-2", "01")
util.regroup.setSubgroupToPrototype("aai-strongbox-passive-provider", "logistic-container-2", "02")
util.regroup.setSubgroupToPrototype("aai-strongbox-active-provider", "logistic-container-2", "03")
util.regroup.setSubgroupToPrototype("aai-strongbox-storage", "logistic-container-2", "04")
util.regroup.setSubgroupToPrototype("aai-strongbox-buffer", "logistic-container-2", "05")
util.regroup.setSubgroupToPrototype("aai-strongbox-requester", "logistic-container-2", "06")

-- logistic-container-4
util.regroup.setSubgroupToPrototype("aai-storehouse", "logistic-container-4", "01")
util.regroup.setSubgroupToPrototype("aai-storehouse-passive-provider", "logistic-container-4", "02")
util.regroup.setSubgroupToPrototype("aai-storehouse-active-provider", "logistic-container-4", "03")
util.regroup.setSubgroupToPrototype("aai-storehouse-storage", "logistic-container-4", "04")
util.regroup.setSubgroupToPrototype("aai-storehouse-buffer", "logistic-container-4", "05")
util.regroup.setSubgroupToPrototype("aai-storehouse-requester", "logistic-container-4", "06")

-- logistic-container-6
util.regroup.setSubgroupToPrototype("aai-warehouse", "logistic-container-6", "01")
util.regroup.setSubgroupToPrototype("aai-warehouse-passive-provider", "logistic-container-6", "02")
util.regroup.setSubgroupToPrototype("aai-warehouse-active-provider", "logistic-container-6", "03")
util.regroup.setSubgroupToPrototype("aai-warehouse-storage", "logistic-container-6", "04")
util.regroup.setSubgroupToPrototype("aai-warehouse-buffer", "logistic-container-6", "05")
util.regroup.setSubgroupToPrototype("aai-warehouse-requester", "logistic-container-6", "06")

-- logistic-storage
util.regroup.setSubgroupToPrototype("kr-shelter", "logistic-storage", "01")
util.regroup.setSubgroupToPrototype("memory-unit-se2", "logistic-storage", "02")
util.regroup.setSubgroupToPrototype("fluid-memory-unit", "logistic-storage", "03")
util.regroup.setSubgroupToPrototype("se-linked-container", "logistic-storage", "04")

-- logistic-belt
util.regroup.setSubgroupToPrototype("kr-loader", "logistic-belt", "01")
util.regroup.setSubgroupToPrototype("kr-fast-loader", "logistic-belt", "02")
util.regroup.setSubgroupToPrototype("kr-express-loader", "logistic-belt", "03")
util.regroup.setSubgroupToPrototype("kr-advanced-loader", "logistic-belt", "04")
util.regroup.setSubgroupToPrototype("kr-superior-loader", "logistic-belt", "05")
util.regroup.setSubgroupToPrototype("kr-se-loader", "logistic-belt", "06")
util.regroup.setSubgroupToPrototype("kr-se-deep-space-loader-black", "logistic-belt", "07")

-- logistic-transport-belt
util.regroup.setSubgroupToPrototype("transport-belt", "logistic-transport-belt", "01")
util.regroup.setSubgroupToPrototype("fast-transport-belt", "logistic-transport-belt", "02")
util.regroup.setSubgroupToPrototype("express-transport-belt", "logistic-transport-belt", "03")
util.regroup.setSubgroupToPrototype("kr-advanced-transport-belt", "logistic-transport-belt", "04")
util.regroup.setSubgroupToPrototype("kr-superior-transport-belt", "logistic-transport-belt", "05")
util.regroup.setSubgroupToPrototype("se-space-transport-belt", "logistic-transport-belt", "06")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt", "logistic-transport-belt", "07")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-black", "logistic-transport-belt", "08")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-blue", "logistic-transport-belt", "09")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-cyan", "logistic-transport-belt", "10")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-green", "logistic-transport-belt", "11")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-magenta", "logistic-transport-belt", "12")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-red", "logistic-transport-belt", "13")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-white", "logistic-transport-belt", "14")
util.regroup.setSubgroupToPrototype("se-deep-space-transport-belt-yellow", "logistic-transport-belt", "15")

-- logistic-underground-belt
util.regroup.setSubgroupToPrototype("underground-belt", "logistic-underground-belt", "01")
util.regroup.setSubgroupToPrototype("fast-underground-belt", "logistic-underground-belt", "02")
util.regroup.setSubgroupToPrototype("express-underground-belt", "logistic-underground-belt", "03")
util.regroup.setSubgroupToPrototype("kr-advanced-underground-belt", "logistic-underground-belt", "04")
util.regroup.setSubgroupToPrototype("kr-superior-underground-belt", "logistic-underground-belt", "05")
util.regroup.setSubgroupToPrototype("se-space-underground-belt", "logistic-underground-belt", "06")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt", "logistic-underground-belt", "07")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-black", "logistic-underground-belt", "08")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-blue", "logistic-underground-belt", "09")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-cyan", "logistic-underground-belt", "10")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-green", "logistic-underground-belt", "11")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-magenta", "logistic-underground-belt", "12")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-red", "logistic-underground-belt", "13")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-white", "logistic-underground-belt", "14")
util.regroup.setSubgroupToPrototype("se-deep-space-underground-belt-yellow", "logistic-underground-belt", "15")

-- logistic-splitter
util.regroup.setSubgroupToPrototype("splitter", "logistic-splitter", "01")
util.regroup.setSubgroupToPrototype("fast-splitter", "logistic-splitter", "02")
util.regroup.setSubgroupToPrototype("express-splitter", "logistic-splitter", "03")
util.regroup.setSubgroupToPrototype("kr-advanced-splitter", "logistic-splitter", "04")
util.regroup.setSubgroupToPrototype("kr-superior-splitter", "logistic-splitter", "05")
util.regroup.setSubgroupToPrototype("se-space-splitter", "logistic-splitter", "06")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter", "logistic-splitter", "07")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-black", "logistic-splitter", "08")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-blue", "logistic-splitter", "09")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-cyan", "logistic-splitter", "10")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-green", "logistic-splitter", "11")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-magenta", "logistic-splitter", "12")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-red", "logistic-splitter", "13")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-white", "logistic-splitter", "14")
util.regroup.setSubgroupToPrototype("se-deep-space-splitter-yellow", "logistic-splitter", "15")

-- logistic-inserter
util.regroup.setSubgroupToPrototype("burner-inserter", "logistic-inserter", "01")
util.regroup.setSubgroupToPrototype("inserter", "logistic-inserter", "02")
util.regroup.setSubgroupToPrototype("long-handed-inserter", "logistic-inserter", "03")
util.regroup.setSubgroupToPrototype("fast-inserter", "logistic-inserter", "04")
util.regroup.setSubgroupToPrototype("filter-inserter", "logistic-inserter", "05")
util.regroup.setSubgroupToPrototype("stack-inserter", "logistic-inserter", "06")
util.regroup.setSubgroupToPrototype("stack-filter-inserter", "logistic-inserter", "07")
util.regroup.setSubgroupToPrototype("kr-superior-inserter", "logistic-inserter", "08")
util.regroup.setSubgroupToPrototype("kr-superior-long-inserter", "logistic-inserter", "09")
util.regroup.setSubgroupToPrototype("kr-superior-filter-inserter", "logistic-inserter", "10")
util.regroup.setSubgroupToPrototype("kr-superior-long-filter-inserter", "logistic-inserter", "11")

-- logistic-cranes
util.regroup.setSubgroupToPrototype("nco-crane", "logistic-cranes", "01")
util.regroup.setSubgroupToPrototype("nco-wide-crane", "logistic-cranes", "02")
util.regroup.setSubgroupToPrototype("nco-filter-crane", "logistic-cranes", "03")
util.regroup.setSubgroupToPrototype("nco-wide-filter-crane", "logistic-cranes", "04")
util.regroup.setSubgroupToPrototype("nco-superior-crane", "logistic-cranes", "05")
util.regroup.setSubgroupToPrototype("nco-superior-wide-crane", "logistic-cranes", "06")
util.regroup.setSubgroupToPrototype("nco-superior-filter-crane", "logistic-cranes", "07")
util.regroup.setSubgroupToPrototype("nco-superior-wide-filter-crane", "logistic-cranes", "08")

-- logistic-pole-middle
util.regroup.setSubgroupToPrototype("small-electric-pole", "logistic-pole-middle", "01")
util.regroup.setSubgroupToPrototype("lighted-small-electric-pole", "logistic-pole-middle", "02")
util.regroup.setSubgroupToPrototype("small-iron-electric-pole", "logistic-pole-middle", "03")
util.regroup.setSubgroupToPrototype("lighted-small-iron-electric-pole", "logistic-pole-middle", "04")
util.regroup.setSubgroupToPrototype("medium-electric-pole", "logistic-pole-middle", "05")
util.regroup.setSubgroupToPrototype("lighted-medium-electric-pole", "logistic-pole-middle", "06")
util.regroup.setSubgroupToPrototype("se-addon-power-pole", "logistic-pole-middle", "07")
util.regroup.setSubgroupToPrototype("lighted-se-addon-power-pole", "logistic-pole-middle", "08")

-- logistic-pole-big
util.regroup.setSubgroupToPrototype("bi-wooden-pole-big", "logistic-pole-big", "01")
util.regroup.setSubgroupToPrototype("lighted-bi-wooden-pole-big", "logistic-pole-big", "02")
util.regroup.setSubgroupToPrototype("bi-wooden-pole-huge", "logistic-pole-big", "03")
util.regroup.setSubgroupToPrototype("lighted-bi-wooden-pole-huge", "logistic-pole-big", "04")
util.regroup.setSubgroupToPrototype("big-electric-pole", "logistic-pole-big", "05")
util.regroup.setSubgroupToPrototype("lighted-big-electric-pole", "logistic-pole-big", "06")
util.regroup.setSubgroupToPrototype("extreme_power_pole", "logistic-pole-big", "07")
util.regroup.setSubgroupToPrototype("lighted-extreme_power_pole", "logistic-pole-big", "08")
util.regroup.setSubgroupToPrototype("se-pylon", "logistic-pole-big", "09")
util.regroup.setSubgroupToPrototype("lighted-se-pylon", "logistic-pole-big", "10")
util.regroup.setSubgroupToPrototype("se-pylon-construction", "logistic-pole-big", "11")
util.regroup.setSubgroupToPrototype("lighted-se-pylon-construction", "logistic-pole-big", "12")

-- logistic-pole-substation
util.regroup.setSubgroupToPrototype("substation", "logistic-pole-substation", "01")
util.regroup.setSubgroupToPrototype("lighted-substation", "logistic-pole-substation", "02")
util.regroup.setSubgroupToPrototype("kr-substation-mk2", "logistic-pole-substation", "03")
util.regroup.setSubgroupToPrototype("lighted-kr-substation-mk2", "logistic-pole-substation", "04")
util.regroup.setSubgroupToPrototype("bi-large-substation", "logistic-pole-substation", "05")
util.regroup.setSubgroupToPrototype("lighted-bi-large-substation", "logistic-pole-substation", "06")
util.regroup.setSubgroupToPrototype("se-pylon-substation", "logistic-pole-substation", "07")
util.regroup.setSubgroupToPrototype("lighted-se-pylon-substation", "logistic-pole-substation", "08")
util.regroup.setSubgroupToPrototype("se-pylon-construction-radar", "logistic-pole-substation", "09")
util.regroup.setSubgroupToPrototype("lighted-se-pylon-construction-radar", "logistic-pole-substation", "10")
util.regroup.setSubgroupToPrototype("kr-tesla-coil", "logistic-pole-substation", "11")
util.regroup.setSubgroupToPrototype("kr-planetary-teleporter", "logistic-pole-substation", "12")

-- logistic-drones
util.regroup.setSubgroupToPrototype("logistic-robot", "logistic-drones", "01")
util.regroup.setSubgroupToPrototype("construction-robot", "logistic-drones", "02")
util.regroup.setSubgroupToPrototype("fu_robo_logistic_item", "logistic-drones", "03")
util.regroup.setSubgroupToPrototype("fu_robo_logistic_recipe", "logistic-drones", "03")
util.regroup.setSubgroupToPrototype("fu_robo_construction_item", "logistic-drones", "04")
util.regroup.setSubgroupToPrototype("fu_robo_construction_recipe", "logistic-drones", "04")

-- logistic-network
util.regroup.setSubgroupToPrototype("roboport", "logistic-network", "01")
util.regroup.setSubgroupToPrototype("fi_robo_charger_item", "logistic-network", "02")
util.regroup.setSubgroupToPrototype("fi_robo_charger_recipe", "logistic-network", "03")
util.regroup.setSubgroupToPrototype("fi_robo_port_item", "logistic-network", "04")
util.regroup.setSubgroupToPrototype("fi_robo_port_recipe", "logistic-network", "05")
util.regroup.setSubgroupToPrototype("kr-small-roboport", "logistic-network", "06")
util.regroup.setSubgroupToPrototype("kr-large-roboport", "logistic-network", "07")
util.regroup.setSubgroupToPrototype("se-supercharger", "logistic-network", "08")

-- logistic-circuit-network
util.regroup.setSubgroupToPrototype("small-lamp", "logistic-circuit-network", "01")
util.regroup.setSubgroupToPrototype("nixie-tube", "logistic-circuit-network", "02")
util.regroup.setSubgroupToPrototype("nixie-tube-alpha", "logistic-circuit-network", "03")
util.regroup.setSubgroupToPrototype("nixie-tube-small", "logistic-circuit-network", "04")
util.regroup.setSubgroupToPrototype("arithmetic-combinator", "logistic-circuit-network", "05")
util.regroup.setSubgroupToPrototype("decider-combinator", "logistic-circuit-network", "06")
util.regroup.setSubgroupToPrototype("constant-combinator", "logistic-circuit-network", "07")
util.regroup.setSubgroupToPrototype("ltn-combinator", "logistic-circuit-network", "08")
util.regroup.setSubgroupToPrototype("se-cme-combinator", "logistic-circuit-network", "09")
util.regroup.setSubgroupToPrototype("power-switch", "logistic-circuit-network", "10")
util.regroup.setSubgroupToPrototype("programmable-speaker", "logistic-circuit-network", "11")
util.regroup.setSubgroupToPrototype("aai-signal-sender", "logistic-circuit-network", "12")
util.regroup.setSubgroupToPrototype("aai-signal-receiver", "logistic-circuit-network", "13")

-- logistic-rocket
util.regroup.setSubgroupToPrototype("se-space-probe-rocket-silo", "logistic-rocket", "01")
util.regroup.setSubgroupToPrototype("se-rocket-launch-pad", "logistic-rocket", "02")
util.regroup.setSubgroupToPrototype("se-rocket-landing-pad", "logistic-rocket", "03")
util.regroup.setSubgroupToPrototype("se-space-capsule", "logistic-rocket", "04")
util.regroup.setSubgroupToPrototype("se-space-capsule-refurbish", "logistic-rocket", "05")
util.regroup.setSubgroupToPrototype("se-delivery-cannon", "logistic-rocket", "06")
util.regroup.setSubgroupToPrototype("se-delivery-cannon-chest", "logistic-rocket", "07")
util.regroup.setSubgroupToPrototype("se-space-elevator", "logistic-rocket", "08")
