local util = require("functions/util")

util.regroup.create_subgroup("science-pack", "science", "raw-01")

util.regroup.create_subgroup("248k-fu-pack-1", "science", "raw-02")
util.regroup.create_subgroup("248k-fu-pack-2", "science", "raw-03")

util.regroup.create_subgroup("248k-gr-common", "science", "raw-04")
util.regroup.create_subgroup("248k-gr-data", "science", "raw-05")
util.regroup.create_subgroup("248k-gr-pack", "science", "raw-06")
util.regroup.create_subgroup("248k-gr-element", "science", "raw-07")

util.regroup.create_subgroup("data-generic", "science", "raw-08")
util.regroup.create_subgroup("data-significant", "science", "raw-09")

util.regroup.create_subgroup("data-catalogue-astronomic", "science", "raw-10")
util.regroup.create_subgroup("data-astronomic", "science", "raw-11")
util.regroup.create_subgroup("astronomic-science-pack", "science", "raw-12")

util.regroup.create_subgroup("data-catalogue-biological", "science", "raw-13")
util.regroup.create_subgroup("data-biological", "science", "raw-14")
util.regroup.create_subgroup("biological-science-pack", "science", "raw-15")

util.regroup.create_subgroup("data-catalogue-energy", "science", "raw-16")
util.regroup.create_subgroup("data-energy", "science", "raw-17")
util.regroup.create_subgroup("energy-science-pack", "science", "raw-18")

util.regroup.create_subgroup("data-catalogue-material", "science", "raw-19")
util.regroup.create_subgroup("data-material", "science", "raw-20")
util.regroup.create_subgroup("material-science-pack", "science", "raw-21")

util.regroup.create_subgroup("data-catalogue-matter", "science", "raw-22")
util.regroup.create_subgroup("data-matter", "science", "raw-23")
util.regroup.create_subgroup("matter-science-pack", "science", "raw-24")

util.regroup.create_subgroup("data-catalogue-advanced", "science", "raw-25")
util.regroup.create_subgroup("data-advanced", "science", "raw-26")
util.regroup.create_subgroup("advanced-science-pack", "science", "raw-27")

util.regroup.create_subgroup("data-catalogue-deep", "science", "raw-28")
util.regroup.create_subgroup("data-deep", "science", "raw-29")
util.regroup.create_subgroup("deep-science-pack", "science", "raw-30")

-- 248k-fu-pack-1
util.regroup.set_subgroup_to_prototype("fu_materials_fusion_card", "248k-fu-pack-1", "01")
util.regroup.set_subgroup_to_prototype("fu_fusion_card_1_recipe", "248k-fu-pack-1", "02")
util.regroup.set_subgroup_to_prototype("fu_fusion_card_2_recipe", "248k-fu-pack-1", "03")
util.regroup.set_subgroup_to_prototype("fu_fusion_card_4_recipe", "248k-fu-pack-1", "04")
util.regroup.set_subgroup_to_prototype("fu_fusion_card_5_recipe", "248k-fu-pack-1", "05")
util.regroup.set_subgroup_to_prototype("fu_fusion_card_7_recipe", "248k-fu-pack-1", "06")
util.regroup.set_subgroup_to_prototype("fu_materials_laser_card", "248k-fu-pack-1", "07")
util.regroup.set_subgroup_to_prototype("fu_laser_card_recipe", "248k-fu-pack-1", "08")
util.regroup.set_subgroup_to_prototype("fu_materials_magnet_card", "248k-fu-pack-1", "09")
util.regroup.set_subgroup_to_prototype("fu_magnet_card_recipe", "248k-fu-pack-1", "10")
util.regroup.set_subgroup_to_prototype("fu_materials_plasma_card", "248k-fu-pack-1", "11")
util.regroup.set_subgroup_to_prototype("fu_plasma_card_recipe", "248k-fu-pack-1", "12")
util.regroup.set_subgroup_to_prototype("fu_tech_sign_item", "248k-fu-pack-1", "13")
util.regroup.set_subgroup_to_prototype("fu_tech_sign_recipe", "248k-fu-pack-1", "14")

-- 248k-fu-pack-2
util.regroup.set_subgroup_to_prototype("fu_space_probe_data_card_1_item", "248k-fu-pack-2", "01")
util.regroup.set_subgroup_to_prototype("fu_space_probe_data_card_2_item", "248k-fu-pack-2", "02")
util.regroup.set_subgroup_to_prototype("fu_space_probe_data_card_3_item", "248k-fu-pack-2", "03")
util.regroup.set_subgroup_to_prototype("fu_space_probe_ore_item", "248k-fu-pack-2", "04")
util.regroup.set_subgroup_to_prototype("fu_space_probe_up_matter_item", "248k-fu-pack-2", "05")
util.regroup.set_subgroup_to_prototype("fu_space_probe_down_matter_item", "248k-fu-pack-2", "06")
util.regroup.set_subgroup_to_prototype("fu_space_probe_ore_recipe", "248k-fu-pack-2", "07")
util.regroup.set_subgroup_to_prototype("gr_kovarex_2_recipe", "248k-fu-pack-2", "08")
util.regroup.set_subgroup_to_prototype("gr_kovarex_recipe", "248k-fu-pack-2", "09")
util.regroup.set_subgroup_to_prototype("fu_space_probe_science_item", "248k-fu-pack-2", "10")
util.regroup.set_subgroup_to_prototype("fu_space_probe_science_recipe", "248k-fu-pack-2", "11")
util.regroup.set_subgroup_to_prototype("fu_space_probe_science_item_1", "248k-fu-pack-2", "11")

-- 248k-gr-common
util.regroup.set_subgroup_to_prototype("gr_crushed_exotic_recipe", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_crushed_exotic_item", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_stabilizer_recipe", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_stabilizer_item", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_data_recipe", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_data_item", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_stacked_data_recipe", "248k-gr-common", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_stacked_data_item", "248k-gr-common", "01")

-- 248k-gr-data
util.regroup.set_subgroup_to_prototype("gr_red_data_recipe", "248k-gr-data", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_red_data_item", "248k-gr-data", "02")
util.regroup.set_subgroup_to_prototype("gr_green_data_recipe", "248k-gr-data", "03")
util.regroup.set_subgroup_to_prototype("gr_materials_green_data_item", "248k-gr-data", "04")
util.regroup.set_subgroup_to_prototype("gr_blue_data_recipe", "248k-gr-data", "05")
util.regroup.set_subgroup_to_prototype("gr_materials_blue_data_item", "248k-gr-data", "06")
util.regroup.set_subgroup_to_prototype("gr_purple_data_recipe", "248k-gr-data", "07")
util.regroup.set_subgroup_to_prototype("gr_materials_purple_data_item", "248k-gr-data", "08")
util.regroup.set_subgroup_to_prototype("gr_yellow_data_recipe", "248k-gr-data", "09")
util.regroup.set_subgroup_to_prototype("gr_materials_yellow_data_item", "248k-gr-data", "10")
util.regroup.set_subgroup_to_prototype("gr_grey_data_recipe", "248k-gr-data", "11")
util.regroup.set_subgroup_to_prototype("gr_materials_grey_data_item", "248k-gr-data", "12")
util.regroup.set_subgroup_to_prototype("gr_white_data_recipe", "248k-gr-data", "13")
util.regroup.set_subgroup_to_prototype("gr_materials_white_data_item", "248k-gr-data", "14")

-- 248k-gr-pack
util.regroup.set_subgroup_to_prototype("gr_red_pack_recipe", "248k-gr-pack", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_red_pack_item", "248k-gr-pack", "02")
util.regroup.set_subgroup_to_prototype("gr_green_pack_recipe", "248k-gr-pack", "03")
util.regroup.set_subgroup_to_prototype("gr_materials_green_pack_item", "248k-gr-pack", "04")
util.regroup.set_subgroup_to_prototype("gr_blue_pack_recipe", "248k-gr-pack", "05")
util.regroup.set_subgroup_to_prototype("gr_materials_blue_pack_item", "248k-gr-pack", "06")
util.regroup.set_subgroup_to_prototype("gr_purple_pack_recipe", "248k-gr-pack", "07")
util.regroup.set_subgroup_to_prototype("gr_materials_purple_pack_item", "248k-gr-pack", "08")
util.regroup.set_subgroup_to_prototype("gr_yellow_pack_recipe", "248k-gr-pack", "09")
util.regroup.set_subgroup_to_prototype("gr_materials_yellow_pack_item", "248k-gr-pack", "10")
util.regroup.set_subgroup_to_prototype("gr_grey_pack_recipe", "248k-gr-pack", "11")
util.regroup.set_subgroup_to_prototype("gr_materials_grey_pack_item", "248k-gr-pack", "12")
util.regroup.set_subgroup_to_prototype("gr_white_pack_recipe", "248k-gr-pack", "13")
util.regroup.set_subgroup_to_prototype("gr_materials_white_pack_item", "248k-gr-pack", "14")

-- 248k-gr-element
util.regroup.set_subgroup_to_prototype("gr_red_recipe", "248k-gr-element", "01")
util.regroup.set_subgroup_to_prototype("gr_materials_red_item", "248k-gr-element", "02")
util.regroup.set_subgroup_to_prototype("gr_green_recipe", "248k-gr-element", "03")
util.regroup.set_subgroup_to_prototype("gr_materials_green_item", "248k-gr-element", "04")
util.regroup.set_subgroup_to_prototype("gr_blue_recipe", "248k-gr-element", "05")
util.regroup.set_subgroup_to_prototype("gr_materials_blue_item", "248k-gr-element", "06")
util.regroup.set_subgroup_to_prototype("gr_purple_recipe", "248k-gr-element", "07")
util.regroup.set_subgroup_to_prototype("gr_materials_purple_item", "248k-gr-element", "08")
util.regroup.set_subgroup_to_prototype("gr_yellow_recipe", "248k-gr-element", "09")
util.regroup.set_subgroup_to_prototype("gr_materials_yellow_item", "248k-gr-element", "10")
util.regroup.set_subgroup_to_prototype("gr_grey_recipe", "248k-gr-element", "11")
util.regroup.set_subgroup_to_prototype("gr_materials_grey_item", "248k-gr-element", "12")
util.regroup.set_subgroup_to_prototype("gr_white_recipe", "248k-gr-element", "13")
util.regroup.set_subgroup_to_prototype("gr_materials_white_item", "248k-gr-element", "14")
