local util = require("functions/util")

data:extend {
    {
        type = "item-group",
        name = "space-intermediate-products",
        icon = "__space-exploration-graphics__/graphics/technology/spaceship.png",
        icon_size = 128,
        icon_mipmaps = 1,
    },
}

util.regroup.createSubgroup("space-intermediate-product-spaceship-structure", "space-intermediate-products", "raw-01")
util.regroup.createSubgroup("space-intermediate-product-satellite", "space-intermediate-products", "raw-02")
util.regroup.createSubgroup("space-intermediate-product-specialist-assembling", "space-intermediate-products", "raw-03")
util.regroup.createSubgroup("space-intermediate-product-observation-frame", "space-intermediate-products", "raw-04")
util.regroup.createSubgroup("space-intermediate-product-thermofluid", "space-intermediate-products", "raw-05")
util.regroup.createSubgroup("space-intermediate-product-specimen", "space-intermediate-products", "raw-06")
util.regroup.createSubgroup("space-intermediate-product-arcosphere", "space-intermediate-products", "raw-07")
util.regroup.createSubgroup("space-intermediate-product-arcosphere-folding", "space-intermediate-products", "raw-08")
util.regroup.createSubgroup("space-intermediate-product-canister-fill", "space-intermediate-products", "raw-09")
util.regroup.createSubgroup("space-intermediate-product-stream", "space-intermediate-products", "raw-10")
util.regroup.createSubgroup("space-intermediate-product-gel", "space-intermediate-products", "raw-11")
util.regroup.createSubgroup("space-intermediate-product-sludge", "space-intermediate-products", "raw-12")
util.regroup.createSubgroup("space-intermediate-product-particle-stream", "space-intermediate-products", "raw-13")
util.regroup.createSubgroup("space-intermediate-product-materialisation", "space-intermediate-products", "raw-14")
util.regroup.createSubgroup("basic-matter-conversion", "space-intermediate-products", "raw-15")
util.regroup.createSubgroup("matter-conversion", "space-intermediate-products", "raw-16")

-- space-intermediate-product-spaceship-structure
util.regroup.setSubgroupToPrototype("se-spaceship-console", "space-intermediate-product-spaceship-structure", "01")
util.regroup.setSubgroupToPrototype("se-spaceship-floor", "space-intermediate-product-spaceship-structure", "02")
util.regroup.setSubgroupToPrototype("se-spaceship-wall", "space-intermediate-product-spaceship-structure", "03")
util.regroup.setSubgroupToPrototype("se-spaceship-gate", "space-intermediate-product-spaceship-structure", "04")
util.regroup.setSubgroupToPrototype("se-spaceship-clamp", "space-intermediate-product-spaceship-structure", "05")
util.regroup.setSubgroupToPrototype("se-spaceship-rocket-engine", "space-intermediate-product-spaceship-structure", "06")
util.regroup.setSubgroupToPrototype("se-spaceship-rocket-booster-tank", "space-intermediate-product-spaceship-structure", "07")
util.regroup.setSubgroupToPrototype("se-spaceship-ion-engine", "space-intermediate-product-spaceship-structure", "08")
util.regroup.setSubgroupToPrototype("se-spaceship-ion-booster-tank", "space-intermediate-product-spaceship-structure", "09")
util.regroup.setSubgroupToPrototype("se-spaceship-antimatter-engine", "space-intermediate-product-spaceship-structure", "10")
util.regroup.setSubgroupToPrototype("se-spaceship-antimatter-booster-tank", "space-intermediate-product-spaceship-structure", "11")

-- space-intermediate-product-satellite
util.regroup.setSubgroupToPrototype("se-space-probe-rocket", "space-intermediate-product-satellite", "01")
util.regroup.setSubgroupToPrototype("satellite", "space-intermediate-product-satellite", "02")
util.regroup.setSubgroupToPrototype("gps-satellite", "space-intermediate-product-satellite", "03")
util.regroup.setSubgroupToPrototype("fu_space_probe_sputnik_recipe", "space-intermediate-product-satellite", "04")
util.regroup.setSubgroupToPrototype("fu_space_probe_sputnik_item", "space-intermediate-product-satellite", "05")
util.regroup.setSubgroupToPrototype("fu_space_probe_probe_recipe", "space-intermediate-product-satellite", "06")
util.regroup.setSubgroupToPrototype("fu_space_probe_probe_item", "space-intermediate-product-satellite", "07")
util.regroup.setSubgroupToPrototype("fu_space_probe_deep_probe_recipe", "space-intermediate-product-satellite", "08")
util.regroup.setSubgroupToPrototype("fu_space_probe_deep_probe_item", "space-intermediate-product-satellite", "09")


-- space-intermediate-product-specialist-assembling
util.regroup.setSubgroupToPrototype("se-scrap", "space-intermediate-product-specialist-assembling", "01")
util.regroup.setSubgroupToPrototype("se-contaminated-scrap", "space-intermediate-product-specialist-assembling", "02")
util.regroup.setSubgroupToPrototype("se-space-mirror", "space-intermediate-product-specialist-assembling", "03")
util.regroup.setSubgroupToPrototype("se-space-mirror-alternate", "space-intermediate-product-specialist-assembling", "04")
util.regroup.setSubgroupToPrototype("se-gammaray-detector", "space-intermediate-product-specialist-assembling", "05")
util.regroup.setSubgroupToPrototype("se-material-testing-pack", "space-intermediate-product-specialist-assembling", "06")
util.regroup.setSubgroupToPrototype("se-naquium-cube", "space-intermediate-product-specialist-assembling", "07")
util.regroup.setSubgroupToPrototype("se-naquium-tessaract", "space-intermediate-product-specialist-assembling", "08")
util.regroup.setSubgroupToPrototype("se-naquium-tessaract-alt", "space-intermediate-product-specialist-assembling", "09")

-- space-intermediate-product-observation-frame
util.regroup.setSubgroupToPrototype("se-observation-frame-blank", "space-intermediate-product-observation-frame", "01")
util.regroup.setSubgroupToPrototype("se-observation-frame-blank-beryllium", "space-intermediate-product-observation-frame", "02")
util.regroup.setSubgroupToPrototype("se-observation-frame-radio", "space-intermediate-product-observation-frame", "03")
util.regroup.setSubgroupToPrototype("se-observation-frame-microwave", "space-intermediate-product-observation-frame", "04")
util.regroup.setSubgroupToPrototype("se-observation-frame-infrared", "space-intermediate-product-observation-frame", "05")
util.regroup.setSubgroupToPrototype("se-observation-frame-visible", "space-intermediate-product-observation-frame", "06")
util.regroup.setSubgroupToPrototype("se-observation-frame-uv", "space-intermediate-product-observation-frame", "07")
util.regroup.setSubgroupToPrototype("se-observation-frame-xray", "space-intermediate-product-observation-frame", "08")
util.regroup.setSubgroupToPrototype("se-observation-frame-gammaray", "space-intermediate-product-observation-frame", "09")

-- space-intermediate-product-thermofluid
util.regroup.setSubgroupToPrototype("se-space-coolant", "space-intermediate-product-thermofluid", "01")
util.regroup.setSubgroupToPrototype("se-space-coolant-cryonite", "space-intermediate-product-thermofluid", "02")
util.regroup.setSubgroupToPrototype("se-radiating-space-coolant-slow", "space-intermediate-product-thermofluid", "03")
util.regroup.setSubgroupToPrototype("se-radiating-space-coolant-normal", "space-intermediate-product-thermofluid", "04")
util.regroup.setSubgroupToPrototype("se-radiating-space-coolant-fast", "space-intermediate-product-thermofluid", "05")
util.regroup.setSubgroupToPrototype("se-space-coolant-cold", "space-intermediate-product-thermofluid", "06")
util.regroup.setSubgroupToPrototype("se-space-coolant-cold-cryonite", "space-intermediate-product-thermofluid", "07")
util.regroup.setSubgroupToPrototype("se-space-coolant-supercooled", "space-intermediate-product-thermofluid", "08")
util.regroup.setSubgroupToPrototype("se-space-coolant-supercooled-cryonite", "space-intermediate-product-thermofluid", "09")

-- space-intermediate-product-specimen
util.regroup.setSubgroupToPrototype("se-specimen-fish", "space-intermediate-product-specimen", "01")
util.regroup.setSubgroupToPrototype("se-specimen-wood", "space-intermediate-product-specimen", "02")
util.regroup.setSubgroupToPrototype("se-nutrient-vat", "space-intermediate-product-specimen", "03")
util.regroup.setSubgroupToPrototype("se-bioculture", "space-intermediate-product-specimen", "04")
util.regroup.setSubgroupToPrototype("se-experimental-bioculture", "space-intermediate-product-specimen", "05")
util.regroup.setSubgroupToPrototype("se-specimen", "space-intermediate-product-specimen", "06")
util.regroup.setSubgroupToPrototype("se-experimental-specimen", "space-intermediate-product-specimen", "07")
util.regroup.setSubgroupToPrototype("se-significant-specimen", "space-intermediate-product-specimen", "08")

-- space-intermediate-product-arcosphere
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-in", "space-intermediate-product-arcosphere", "01")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-out", "space-intermediate-product-arcosphere", "02")
util.regroup.setSubgroupToPrototype("se-arcosphere-fracture", "space-intermediate-product-arcosphere", "03")
util.regroup.setSubgroupToPrototype("se-arcosphere-fracture-alt", "space-intermediate-product-arcosphere", "04")
util.regroup.setSubgroupToPrototype("se-arcosphere-collector", "space-intermediate-product-arcosphere", "05")
util.regroup.setSubgroupToPrototype("se-arcosphere", "space-intermediate-product-arcosphere", "06")
util.regroup.setSubgroupToPrototype("se-arcosphere-a", "space-intermediate-product-arcosphere", "07")
util.regroup.setSubgroupToPrototype("se-arcosphere-b", "space-intermediate-product-arcosphere", "08")
util.regroup.setSubgroupToPrototype("se-arcosphere-c", "space-intermediate-product-arcosphere", "09")
util.regroup.setSubgroupToPrototype("se-arcosphere-d", "space-intermediate-product-arcosphere", "10")
util.regroup.setSubgroupToPrototype("se-arcosphere-e", "space-intermediate-product-arcosphere", "11")
util.regroup.setSubgroupToPrototype("se-arcosphere-f", "space-intermediate-product-arcosphere", "12")
util.regroup.setSubgroupToPrototype("se-arcosphere-g", "space-intermediate-product-arcosphere", "13")
util.regroup.setSubgroupToPrototype("se-arcosphere-h", "space-intermediate-product-arcosphere", "14")

-- space-intermediate-product-arcosphere-folding
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-a", "space-intermediate-product-arcosphere-folding", "01")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-b", "space-intermediate-product-arcosphere-folding", "02")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-c", "space-intermediate-product-arcosphere-folding", "03")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-d", "space-intermediate-product-arcosphere-folding", "04")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-e", "space-intermediate-product-arcosphere-folding", "05")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-f", "space-intermediate-product-arcosphere-folding", "06")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-g", "space-intermediate-product-arcosphere-folding", "07")
util.regroup.setSubgroupToPrototype("se-arcosphere-fold-h", "space-intermediate-product-arcosphere-folding", "08")

-- space-intermediate-product-canister-fill
util.regroup.setSubgroupToPrototype("se-canister", "space-intermediate-product-canister-fill", "01")
util.regroup.setSubgroupToPrototype("se-empty-lifesupport-canister", "space-intermediate-product-canister-fill", "02")
util.regroup.setSubgroupToPrototype("se-used-lifesupport-canister", "space-intermediate-product-canister-fill", "03")
util.regroup.setSubgroupToPrototype("se-empty-lifesupport-canister-cleaning", "space-intermediate-product-canister-fill", "04")
util.regroup.setSubgroupToPrototype("se-empty-lifesupport-canister-cleaning-space", "space-intermediate-product-canister-fill", "05")
util.regroup.setSubgroupToPrototype("se-lifesupport-canister", "space-intermediate-product-canister-fill", "06")
util.regroup.setSubgroupToPrototype("se-lifesupport-canister-coal", "space-intermediate-product-canister-fill", "07")
util.regroup.setSubgroupToPrototype("se-lifesupport-canister-fish", "space-intermediate-product-canister-fill", "08")
util.regroup.setSubgroupToPrototype("se-lifesupport-canister-specimen", "space-intermediate-product-canister-fill", "09")
util.regroup.setSubgroupToPrototype("se-magnetic-canister", "space-intermediate-product-canister-fill", "10")
util.regroup.setSubgroupToPrototype("se-plasma-canister-empty", "space-intermediate-product-canister-fill", "11")
util.regroup.setSubgroupToPrototype("se-plasma-canister", "space-intermediate-product-canister-fill", "12")
util.regroup.setSubgroupToPrototype("se-ion-canister-empty", "space-intermediate-product-canister-fill", "13")
util.regroup.setSubgroupToPrototype("se-ion-canister", "space-intermediate-product-canister-fill", "14")
util.regroup.setSubgroupToPrototype("se-empty-antimatter-canister", "space-intermediate-product-canister-fill", "15")
util.regroup.setSubgroupToPrototype("se-antimatter-canister", "space-intermediate-product-canister-fill", "16")

-- space-intermediate-product-stream
util.regroup.setSubgroupToPrototype("se-plasma-stream", "space-intermediate-product-stream", "01")
util.regroup.setSubgroupToPrototype("se-ion-stream", "space-intermediate-product-stream", "02")
util.regroup.setSubgroupToPrototype("se-proton-stream", "space-intermediate-product-stream", "03")
util.regroup.setSubgroupToPrototype("se-particle-stream", "space-intermediate-product-stream", "04")
util.regroup.setSubgroupToPrototype("se-antimatter-stream", "space-intermediate-product-stream", "05")

-- space-intermediate-product-gel
util.regroup.setSubgroupToPrototype("se-chemical-gel", "space-intermediate-product-gel", "01")
util.regroup.setSubgroupToPrototype("se-nutrient-gel", "space-intermediate-product-gel", "02")
util.regroup.setSubgroupToPrototype("se-nutrient-gel-methane", "space-intermediate-product-gel", "03")
util.regroup.setSubgroupToPrototype("se-neural-gel", "space-intermediate-product-gel", "04")
util.regroup.setSubgroupToPrototype("se-neural-gel-2", "space-intermediate-product-gel", "05")

-- space-intermediate-product-sludge
util.regroup.setSubgroupToPrototype("se-bio-sludge", "space-intermediate-product-sludge", "01")
util.regroup.setSubgroupToPrototype("se-bio-sludge-crude-oil", "space-intermediate-product-sludge", "02")
util.regroup.setSubgroupToPrototype("se-bio-sludge-from-biomass", "space-intermediate-product-sludge", "03")
util.regroup.setSubgroupToPrototype("se-bio-sludge-from-wood", "space-intermediate-product-sludge", "04")
util.regroup.setSubgroupToPrototype("se-bio-sludge-from-fish", "space-intermediate-product-sludge", "05")
util.regroup.setSubgroupToPrototype("se-bio-sludge-from-vitamelange", "space-intermediate-product-sludge", "06")
util.regroup.setSubgroupToPrototype("se-bio-sludge-decontamination", "space-intermediate-product-sludge", "07")

-- space-intermediate-product-particle-stream
util.regroup.setSubgroupToPrototype("se-kr-experimental-matter-processing", "space-intermediate-product-particle-stream", "01")
util.regroup.setSubgroupToPrototype("se-kr-stone-to-particle-stream", "space-intermediate-product-particle-stream", "02")
util.regroup.setSubgroupToPrototype("se-kr-iron-to-particle-stream", "space-intermediate-product-particle-stream", "03")
util.regroup.setSubgroupToPrototype("se-kr-copper-to-particle-stream", "space-intermediate-product-particle-stream", "04")
util.regroup.setSubgroupToPrototype("se-kr-uranium-to-particle-stream", "space-intermediate-product-particle-stream", "05")
util.regroup.setSubgroupToPrototype("se-kr-rare-metals-to-particle-stream", "space-intermediate-product-particle-stream", "06")
util.regroup.setSubgroupToPrototype("aluminum-ore-to-particle-stream", "space-intermediate-product-particle-stream", "07")
util.regroup.setSubgroupToPrototype("lead-ore-to-particle-stream", "space-intermediate-product-particle-stream", "08")
util.regroup.setSubgroupToPrototype("flake-graphite-to-particle-stream", "space-intermediate-product-particle-stream", "09")
util.regroup.setSubgroupToPrototype("zircon-to-particle-stream", "space-intermediate-product-particle-stream", "10")
util.regroup.setSubgroupToPrototype("tin-ore-to-particle-stream", "space-intermediate-product-particle-stream", "11")
util.regroup.setSubgroupToPrototype("silver-ore-to-particle-stream", "space-intermediate-product-particle-stream", "12")
util.regroup.setSubgroupToPrototype("titanium-ore-to-particle-stream", "space-intermediate-product-particle-stream", "13")
util.regroup.setSubgroupToPrototype("tungsten-ore-to-particle-stream", "space-intermediate-product-particle-stream", "14")
util.regroup.setSubgroupToPrototype("bismuth-ore-to-particle-stream", "space-intermediate-product-particle-stream", "15")
util.regroup.setSubgroupToPrototype("gold-ore-to-particle-stream", "space-intermediate-product-particle-stream", "16")
util.regroup.setSubgroupToPrototype("se-kr-cryonite-to-particle-stream", "space-intermediate-product-particle-stream", "17")
util.regroup.setSubgroupToPrototype("se-kr-vulcanite-to-particle-stream", "space-intermediate-product-particle-stream", "18")
util.regroup.setSubgroupToPrototype("se-kr-imersite-to-particle-stream", "space-intermediate-product-particle-stream", "19")
util.regroup.setSubgroupToPrototype("se-kr-beryllium-to-particle-stream", "space-intermediate-product-particle-stream", "20")
util.regroup.setSubgroupToPrototype("se-kr-holmium-to-particle-stream", "space-intermediate-product-particle-stream", "21")
util.regroup.setSubgroupToPrototype("se-kr-iridium-to-particle-stream", "space-intermediate-product-particle-stream", "22")

-- space-intermediate-product-materialisation
util.regroup.setSubgroupToPrototype("se-matter-fusion-stone", "space-intermediate-product-materialisation", "01")
util.regroup.setSubgroupToPrototype("se-matter-fusion-iron", "space-intermediate-product-materialisation", "02")
util.regroup.setSubgroupToPrototype("se-matter-fusion-copper", "space-intermediate-product-materialisation", "03")
util.regroup.setSubgroupToPrototype("se-matter-fusion-uranium", "space-intermediate-product-materialisation", "04")
util.regroup.setSubgroupToPrototype("se-matter-fusion-raw-rare-metals", "space-intermediate-product-materialisation", "05")
util.regroup.setSubgroupToPrototype("matter-fusion-aluminum-ore", "space-intermediate-product-materialisation", "06")
util.regroup.setSubgroupToPrototype("matter-fusion-lead-ore", "space-intermediate-product-materialisation", "07")
util.regroup.setSubgroupToPrototype("matter-fusion-flake-graphite", "space-intermediate-product-materialisation", "08")
util.regroup.setSubgroupToPrototype("matter-fusion-zircon", "space-intermediate-product-materialisation", "09")
util.regroup.setSubgroupToPrototype("matter-fusion-tin-ore", "space-intermediate-product-materialisation", "10")
util.regroup.setSubgroupToPrototype("matter-fusion-silver-ore", "space-intermediate-product-materialisation", "11")
util.regroup.setSubgroupToPrototype("matter-fusion-titanium-ore", "space-intermediate-product-materialisation", "12")
util.regroup.setSubgroupToPrototype("matter-fusion-tungsten-ore", "space-intermediate-product-materialisation", "13")
util.regroup.setSubgroupToPrototype("matter-fusion-bismuth-ore", "space-intermediate-product-materialisation", "14")
util.regroup.setSubgroupToPrototype("matter-fusion-gold-ore", "space-intermediate-product-materialisation", "15")
util.regroup.setSubgroupToPrototype("se-matter-fusion-cryonite", "space-intermediate-product-materialisation", "16")
util.regroup.setSubgroupToPrototype("se-matter-fusion-vulcanite", "space-intermediate-product-materialisation", "17")
util.regroup.setSubgroupToPrototype("se-matter-fusion-raw-imersite", "space-intermediate-product-materialisation", "18")
util.regroup.setSubgroupToPrototype("se-matter-fusion-beryllium", "space-intermediate-product-materialisation", "19")
util.regroup.setSubgroupToPrototype("se-matter-fusion-holmium", "space-intermediate-product-materialisation", "20")
util.regroup.setSubgroupToPrototype("se-matter-fusion-iridium", "space-intermediate-product-materialisation", "21")
