local util = require("functions/util")

util.regroup.create_subgroup("combat-tool", "combat", "raw-01")
util.regroup.create_subgroup("combat-defensive-structure", "combat", "raw-02")
util.regroup.create_subgroup("combat-radars-and-rockets", "combat", "raw-03")
util.regroup.create_subgroup("combat-defensive-tool", "combat", "raw-04")
util.regroup.create_subgroup("combat-dart", "combat", "raw-05")
util.regroup.create_subgroup("combat-firearm", "combat", "raw-06")
util.regroup.create_subgroup("combat-shotgun", "combat", "raw-07")
util.regroup.create_subgroup("combat-large-rifle", "combat", "raw-08")
util.regroup.create_subgroup("combat-rifle", "combat", "raw-09")
util.regroup.create_subgroup("combat-flamethrower", "combat", "raw-10")
util.regroup.create_subgroup("combat-se-gun", "combat", "raw-11")
util.regroup.create_subgroup("combat-capsule", "combat", "raw-12")
util.regroup.create_subgroup("combat-cannon", "combat", "raw-13")
util.regroup.create_subgroup("combat-rocket", "combat", "raw-14")
util.regroup.create_subgroup("combat-railgun", "combat", "raw-15")
util.regroup.create_subgroup("combat-rocket-turret", "combat", "raw-16")
util.regroup.create_subgroup("combat-laser", "combat", "raw-17")
util.regroup.create_subgroup("combat-artillery", "combat", "raw-18")
util.regroup.create_subgroup("combat-surface-defense", "combat", "raw-19")
util.regroup.create_subgroup("combat-grenade", "combat", "raw-20")
util.regroup.create_subgroup("combat-biter-capsule", "combat", "raw-21")

-- combat-tool
util.regroup.set_subgroup_to_prototype("repair-pack", "combat-tool", "01")
util.regroup.set_subgroup_to_prototype("copper-repair-pack", "combat-tool", "02")
util.regroup.set_subgroup_to_prototype("copper-repair-recipe", "combat-tool", "02")
util.regroup.set_subgroup_to_prototype("steel-repair-pack", "combat-tool", "03")
util.regroup.set_subgroup_to_prototype("steel-repair-recipe", "combat-tool", "03")
util.regroup.set_subgroup_to_prototype("field-repair-pack", "combat-tool", "04")
util.regroup.set_subgroup_to_prototype("field-repair-recipe", "combat-tool", "04")
util.regroup.set_subgroup_to_prototype("multitool-repair-pack", "combat-tool", "05")
util.regroup.set_subgroup_to_prototype("multitool-repair-recipe", "combat-tool", "05")
util.regroup.set_subgroup_to_prototype("first-aid-kit", "combat-tool", "06")
util.regroup.set_subgroup_to_prototype("first-aid-kit-fish", "combat-tool", "07")
util.regroup.set_subgroup_to_prototype("se-medpack", "combat-tool", "09")
util.regroup.set_subgroup_to_prototype("se-medpack-plastic", "combat-tool", "09")
util.regroup.set_subgroup_to_prototype("se-medpack-2", "combat-tool", "10")
util.regroup.set_subgroup_to_prototype("se-medpack-3", "combat-tool", "11")
util.regroup.set_subgroup_to_prototype("se-medpack-4", "combat-tool", "12")
util.regroup.set_subgroup_to_prototype("gun-nano-emitter", "combat-tool", "13")
util.regroup.set_subgroup_to_prototype("ammo-nano-constructors", "combat-tool", "14")
util.regroup.set_subgroup_to_prototype("ammo-nano-termites", "combat-tool", "15")

-- combat-defensive-structure
util.regroup.set_subgroup_to_prototype("bi-wooden-fence", "combat-defensive-structure", "01")
util.regroup.set_subgroup_to_prototype("stone-wall", "combat-defensive-structure", "02")
util.regroup.set_subgroup_to_prototype("concrete-wall", "combat-defensive-structure", "03")
util.regroup.set_subgroup_to_prototype("steel-wall", "combat-defensive-structure", "04")
util.regroup.set_subgroup_to_prototype("mending-wall-rampant-arsenal", "combat-defensive-structure", "05")
util.regroup.set_subgroup_to_prototype("reinforced-wall-rampant-arsenal", "combat-defensive-structure", "06")
util.regroup.set_subgroup_to_prototype("gate", "combat-defensive-structure", "07")
util.regroup.set_subgroup_to_prototype("mending-gate-rampant-arsenal", "combat-defensive-structure", "08")
util.regroup.set_subgroup_to_prototype("reinforced-gate-rampant-arsenal", "combat-defensive-structure", "09")
util.regroup.set_subgroup_to_prototype("shield-projector", "combat-defensive-structure", "10")

-- radars-and-rockets
util.regroup.set_subgroup_to_prototype("kr-sentinel", "combat-radars-and-rockets", "01")
util.regroup.set_subgroup_to_prototype("radar", "combat-radars-and-rockets", "02")
util.regroup.set_subgroup_to_prototype("advanced-radar", "combat-radars-and-rockets", "03")
util.regroup.set_subgroup_to_prototype("rocket-silo", "combat-radars-and-rockets", "04")
util.regroup.set_subgroup_to_prototype("kr-intergalactic-transceiver", "combat-radars-and-rockets", "05")

-- combat-defensive-tool
util.regroup.set_subgroup_to_prototype("medic-item-rampant-arsenal", "combat-defensive-tool", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-medic-item-rampant-arsenal", "combat-defensive-tool", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-medic-item-rampant-arsenal", "combat-defensive-tool", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-medic-item-rampant-arsenal", "combat-defensive-tool", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-medic-item-rampant-arsenal", "combat-defensive-tool", "014")
util.regroup.set_subgroup_to_prototype("artillery-targeting-remote", "combat-defensive-tool", "02")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-artillery-targeter-atomic-bomb", "combat-defensive-tool", "03")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-artillery-targeter-se-iridium-piledriver",
    "combat-defensive-tool",
    "04")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-artillery-targeter-antimatter-rocket", "combat-defensive-tool",
    "05")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-artillery-targeter-se-plague-bomb", "combat-defensive-tool",
    "06")
util.regroup.set_subgroup_to_prototype("orbital-ion-cannon", "combat-defensive-tool", "07")
util.regroup.set_subgroup_to_prototype("artillery-bombardment-remote", "combat-defensive-tool", "08")
util.regroup.set_subgroup_to_prototype("smart-artillery-bombardment-remote", "combat-defensive-tool", "09")
util.regroup.set_subgroup_to_prototype("smart-artillery-exploration-remote", "combat-defensive-tool", "10")

-- combat-dart
util.regroup.set_subgroup_to_prototype("bi-dart-turret", "combat-dart", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-bi-dart-turret", "combat-dart", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-bi-dart-turret", "combat-dart", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-bi-dart-turret", "combat-dart", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-bi-dart-turret", "combat-dart", "014")
util.regroup.set_subgroup_to_prototype("bi-dart-rifle", "combat-dart", "02")
util.regroup.set_subgroup_to_prototype("bi-dart-magazine-basic", "combat-dart", "03")
util.regroup.set_subgroup_to_prototype("bi-dart-magazine-standard", "combat-dart", "04")
util.regroup.set_subgroup_to_prototype("bi-dart-magazine-enhanced", "combat-dart", "05")
util.regroup.set_subgroup_to_prototype("bi-dart-magazine-poison", "combat-dart", "06")
util.regroup.set_subgroup_to_prototype("bi-seed-bomb-basic", "combat-dart", "07")
util.regroup.set_subgroup_to_prototype("bi-seed-bomb-standard", "combat-dart", "08")
util.regroup.set_subgroup_to_prototype("bi-seed-bomb-advanced", "combat-dart", "09")

-- combat-firearm
util.regroup.set_subgroup_to_prototype("pistol", "combat-firearm", "01")
util.regroup.set_subgroup_to_prototype("firearm-magazine", "combat-firearm", "02")
util.regroup.set_subgroup_to_prototype("pistol-magazine-bismuth", "combat-firearm", "03")
util.regroup.set_subgroup_to_prototype("high-capacity-firearm-magazine", "combat-firearm", "04")
util.regroup.set_subgroup_to_prototype("piercing-rounds-magazine", "combat-firearm", "05")
util.regroup.set_subgroup_to_prototype("high-capacity-piercing-rounds-magazine", "combat-firearm", "06")

-- combat-shotgun
util.regroup.set_subgroup_to_prototype("shotgun-item-rampant-arsenal", "combat-shotgun", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-shotgun-item-rampant-arsenal", "combat-shotgun", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-shotgun-item-rampant-arsenal", "combat-shotgun", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-shotgun-item-rampant-arsenal", "combat-shotgun", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-shotgun-item-rampant-arsenal", "combat-shotgun", "014")
util.regroup.set_subgroup_to_prototype("shotgun", "combat-shotgun", "02")
util.regroup.set_subgroup_to_prototype("combat-shotgun", "combat-shotgun", "03")
util.regroup.set_subgroup_to_prototype("shotgun-shell", "combat-shotgun", "04")
util.regroup.set_subgroup_to_prototype("high-capacity-shotgun-shell", "combat-shotgun", "05")
util.regroup.set_subgroup_to_prototype("piercing-shotgun-shell", "combat-shotgun", "06")
util.regroup.set_subgroup_to_prototype("high-capacity-piercing-shotgun-shell", "combat-shotgun", "07")
util.regroup.set_subgroup_to_prototype("uranium-shotgun-shell", "combat-shotgun", "08")
util.regroup.set_subgroup_to_prototype("uranium-shotgun-recipe", "combat-shotgun", "08")
util.regroup.set_subgroup_to_prototype("high-capacity-uranium-shotgun-shell", "combat-shotgun", "09")
util.regroup.set_subgroup_to_prototype("high-capacity-uranium-shotgun-recipe", "combat-shotgun", "09")
util.regroup.set_subgroup_to_prototype("bio-shotgun-ammo-rampant-arsenal", "combat-shotgun", "10")
util.regroup.set_subgroup_to_prototype("he-shotgun-ammo-rampant-arsenal", "combat-shotgun", "11")
util.regroup.set_subgroup_to_prototype("incendiary-shotgun-ammo-rampant-arsenal", "combat-shotgun", "12")
util.regroup.set_subgroup_to_prototype("uranium-shotgun-ammo-rampant-arsenal", "combat-shotgun", "13")

-- combat-large-rifle
util.regroup.set_subgroup_to_prototype("anti-material-rifle", "combat-large-rifle", "01")
util.regroup.set_subgroup_to_prototype("anti-material-rifle-magazine", "combat-large-rifle", "02")
util.regroup.set_subgroup_to_prototype("armor-piercing-anti-material-rifle-magazine", "combat-large-rifle", "03")
util.regroup.set_subgroup_to_prototype("explosive-rounds-anti-material-rifle-magazine", "combat-large-rifle", "04")
util.regroup.set_subgroup_to_prototype("uranium-anti-material-rifle-magazine", "combat-large-rifle", "05")
util.regroup.set_subgroup_to_prototype("imersite-anti-material-rifle-magazine", "combat-large-rifle", "06")

-- combat-rifle
util.regroup.set_subgroup_to_prototype("gun-turret", "combat-rifle", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-gun-turret", "combat-rifle", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-gun-turret", "combat-rifle", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-gun-turret", "combat-rifle", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-gun-turret", "combat-rifle", "024")
util.regroup.set_subgroup_to_prototype("gun-item-rampant-arsenal", "combat-rifle", "03")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-gun-item-rampant-arsenal", "combat-rifle", "031")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-gun-item-rampant-arsenal", "combat-rifle", "032")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-gun-item-rampant-arsenal", "combat-rifle", "033")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-gun-item-rampant-arsenal", "combat-rifle", "034")
util.regroup.set_subgroup_to_prototype("submachine-gun", "combat-rifle", "04")
util.regroup.set_subgroup_to_prototype("minigun-gun-rampant-arsenal", "combat-rifle", "05")
util.regroup.set_subgroup_to_prototype("rifle-magazine", "combat-rifle", "06")
util.regroup.set_subgroup_to_prototype("rifle-magazine-bismuth", "combat-rifle", "07")
util.regroup.set_subgroup_to_prototype("armor-piercing-rifle-magazine", "combat-rifle", "08")
util.regroup.set_subgroup_to_prototype("explosive-rounds-rifle-magazine", "combat-rifle", "09")
util.regroup.set_subgroup_to_prototype("uranium-rifle-magazine", "combat-rifle", "10")
util.regroup.set_subgroup_to_prototype("high-capacity-uranium-rounds-magazine", "combat-rifle", "11")
util.regroup.set_subgroup_to_prototype("imersite-rifle-magazine", "combat-rifle", "12")
util.regroup.set_subgroup_to_prototype("water-magazine", "combat-rifle", "13")
util.regroup.set_subgroup_to_prototype("water-recipe", "combat-rifle", "13")
util.regroup.set_subgroup_to_prototype("sp-rounds-magazine", "combat-rifle", "14")
util.regroup.set_subgroup_to_prototype("sp-ammo-recipe", "combat-rifle", "14")
util.regroup.set_subgroup_to_prototype("high-capacity-sp-rounds-magazine", "combat-rifle", "15")
util.regroup.set_subgroup_to_prototype("high-capacity-sp-ammo-recipe", "combat-rifle", "15")
util.regroup.set_subgroup_to_prototype("tungsten-rounds-magazine", "combat-rifle", "16")
util.regroup.set_subgroup_to_prototype("tungsten-ammo-recipe", "combat-rifle", "16")
util.regroup.set_subgroup_to_prototype("high-capacity-tungsten-rounds-magazine", "combat-rifle", "17")
util.regroup.set_subgroup_to_prototype("high-capacity-tungsten-ammo-recipe", "combat-rifle", "17")
util.regroup.set_subgroup_to_prototype("fmj-rounds-magazine", "combat-rifle", "18")
util.regroup.set_subgroup_to_prototype("fmj-ammo-recipe", "combat-rifle", "18")
util.regroup.set_subgroup_to_prototype("high-capacity-fmj-rounds-magazine", "combat-rifle", "19")
util.regroup.set_subgroup_to_prototype("high-capacity-fmj-ammo-recipe", "combat-rifle", "19")
util.regroup.set_subgroup_to_prototype("cryonite-rounds-magazine", "combat-rifle", "20")
util.regroup.set_subgroup_to_prototype("cryonite-ammo-recipe", "combat-rifle", "20")
util.regroup.set_subgroup_to_prototype("high-capacity-cryonite-rounds-magazine", "combat-rifle", "21")
util.regroup.set_subgroup_to_prototype("high-capacity-cryonite-ammo-recipe", "combat-rifle", "21")
util.regroup.set_subgroup_to_prototype("cryonite-rounds-magazine", "combat-rifle", "22")
util.regroup.set_subgroup_to_prototype("cryonite-ammo-recipe", "combat-rifle", "22")
util.regroup.set_subgroup_to_prototype("high-capacity-cryonite-rounds-magazine", "combat-rifle", "23")
util.regroup.set_subgroup_to_prototype("high-capacity-cryonite-ammo-recipe", "combat-rifle", "23")
util.regroup.set_subgroup_to_prototype("vulcanite-rounds-magazine", "combat-rifle", "24")
util.regroup.set_subgroup_to_prototype("vulcanite-ammo-recipe", "combat-rifle", "24")
util.regroup.set_subgroup_to_prototype("high-capacity-vulcanite-rounds-magazine", "combat-rifle", "25")
util.regroup.set_subgroup_to_prototype("high-capacity-vulcanite-ammo-recipe", "combat-rifle", "25")
util.regroup.set_subgroup_to_prototype("beryllium-rounds-magazine", "combat-rifle", "26")
util.regroup.set_subgroup_to_prototype("beryllium-ammo-recipe", "combat-rifle", "26")
util.regroup.set_subgroup_to_prototype("high-capacity-beryllium-rounds-magazine", "combat-rifle", "27")
util.regroup.set_subgroup_to_prototype("high-capacity-beryllium-ammo-recipe", "combat-rifle", "27")
util.regroup.set_subgroup_to_prototype("naquium-rounds-magazine", "combat-rifle", "28")
util.regroup.set_subgroup_to_prototype("naquium-ammo-recipe", "combat-rifle", "28")
util.regroup.set_subgroup_to_prototype("high-capacity-naquium-rounds-magazine", "combat-rifle", "29")
util.regroup.set_subgroup_to_prototype("high-capacity-naquium-ammo-recipe", "combat-rifle", "29")
util.regroup.set_subgroup_to_prototype("iridium-rounds-magazine", "combat-rifle", "30")
util.regroup.set_subgroup_to_prototype("iridium-ammo-recipe", "combat-rifle", "30")
util.regroup.set_subgroup_to_prototype("high-capacity-iridium-rounds-magazine", "combat-rifle", "31")
util.regroup.set_subgroup_to_prototype("high-capacity-iridium-ammo-recipe", "combat-rifle", "31")
util.regroup.set_subgroup_to_prototype("fire-rounds-magazine", "combat-rifle", "32")
util.regroup.set_subgroup_to_prototype("fire-ammo-recipe", "combat-rifle", "32")
util.regroup.set_subgroup_to_prototype("high-capacity-fire-rounds-magazine", "combat-rifle", "33")
util.regroup.set_subgroup_to_prototype("high-capacity-fire-ammo-recipe", "combat-rifle", "33")
util.regroup.set_subgroup_to_prototype("acid-rounds-magazine", "combat-rifle", "34")
util.regroup.set_subgroup_to_prototype("acid-ammo-recipe", "combat-rifle", "34")
util.regroup.set_subgroup_to_prototype("high-capacity-acid-rounds-magazine", "combat-rifle", "35")
util.regroup.set_subgroup_to_prototype("high-capacity-acid-ammo-recipe", "combat-rifle", "35")
util.regroup.set_subgroup_to_prototype("he-rounds-magazine", "combat-rifle", "36")
util.regroup.set_subgroup_to_prototype("he-ammo-recipe", "combat-rifle", "36")
util.regroup.set_subgroup_to_prototype("high-capacity-he-rounds-magazine", "combat-rifle", "37")
util.regroup.set_subgroup_to_prototype("high-capacity-he-ammo-recipe", "combat-rifle", "37")
util.regroup.set_subgroup_to_prototype("bio-magazine-ammo-rampant-arsenal", "combat-rifle", "38")
util.regroup.set_subgroup_to_prototype("he-magazine-ammo-rampant-arsenal", "combat-rifle", "39")
util.regroup.set_subgroup_to_prototype("incendiary-magazine-ammo-rampant-arsenal", "combat-rifle", "40")

-- combat-flamethrower
util.regroup.set_subgroup_to_prototype("flamethrower-turret", "combat-flamethrower", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-flamethrower-turret", "combat-flamethrower", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-flamethrower-turret", "combat-flamethrower", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-flamethrower-turret", "combat-flamethrower", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-flamethrower-turret", "combat-flamethrower", "014")
util.regroup.set_subgroup_to_prototype("acid-cannon-rampant-arsenal", "combat-flamethrower", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-acid-cannon-rampant-arsenal", "combat-flamethrower", "024")
util.regroup.set_subgroup_to_prototype("suppression-cannon-item-rampant-arsenal", "combat-flamethrower", "03")
util.regroup.set_subgroup_to_prototype("flamethrower", "combat-flamethrower", "04")
util.regroup.set_subgroup_to_prototype("flamethrower-ammo", "combat-flamethrower", "05")
util.regroup.set_subgroup_to_prototype("napalm-ammo-rampant-arsenal", "combat-flamethrower", "06")

-- combat-capsule
util.regroup.set_subgroup_to_prototype("capsule-item-rampant-arsenal", "combat-capsule", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-capsule-item-rampant-arsenal", "combat-capsule", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-capsule-item-rampant-arsenal", "combat-capsule", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-capsule-item-rampant-arsenal", "combat-capsule", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-capsule-item-rampant-arsenal", "combat-capsule", "041")
util.regroup.set_subgroup_to_prototype("lite-artillery-turret-rampant-arsenal", "combat-capsule", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-lite-artillery-turret-rampant-arsenal", "combat-capsule", "024")
util.regroup.set_subgroup_to_prototype("artillery-targeting-remote-rampant-arsenal", "combat-capsule", "03")
util.regroup.set_subgroup_to_prototype("mortar-gun-rampant-arsenal", "combat-capsule", "04")
util.regroup.set_subgroup_to_prototype("grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "05")
util.regroup.set_subgroup_to_prototype("bio-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "06")
util.regroup.set_subgroup_to_prototype("he-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "07")
util.regroup.set_subgroup_to_prototype("incendiary-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "08")
util.regroup.set_subgroup_to_prototype("cluster-grenade-capsule-ammo-rampant-arsenal", "combat-capsule", "09")
util.regroup.set_subgroup_to_prototype("poison-capsule-ammo-rampant-arsenal", "combat-capsule", "10")
util.regroup.set_subgroup_to_prototype("toxic-capsule-ammo-rampant-arsenal", "combat-capsule", "11")
util.regroup.set_subgroup_to_prototype("slowdown-capsule-ammo-rampant-arsenal", "combat-capsule", "12")
util.regroup.set_subgroup_to_prototype("paralysis-capsule-ammo-rampant-arsenal", "combat-capsule", "13")
util.regroup.set_subgroup_to_prototype("repair-capsule-ammo-rampant-arsenal", "combat-capsule", "14")
util.regroup.set_subgroup_to_prototype("defender-capsule-ammo-rampant-arsenal", "combat-capsule", "15")
util.regroup.set_subgroup_to_prototype("distractor-capsule-ammo-rampant-arsenal", "combat-capsule", "16")
util.regroup.set_subgroup_to_prototype("destroyer-capsule-ammo-rampant-arsenal", "combat-capsule", "17")
util.regroup.set_subgroup_to_prototype("self-repair-capsule-ammo-rampant-arsenal", "combat-capsule", "18")
util.regroup.set_subgroup_to_prototype("land-mine", "combat-capsule", "19")
util.regroup.set_subgroup_to_prototype("bio-landmine-rampant-arsenal", "combat-capsule", "20")
util.regroup.set_subgroup_to_prototype("he-landmine-rampant-arsenal", "combat-capsule", "21")
util.regroup.set_subgroup_to_prototype("incendiary-landmine-rampant-arsenal", "combat-capsule", "22")
util.regroup.set_subgroup_to_prototype("nuclear-landmine-rampant-arsenal", "combat-capsule", "23")
util.regroup.set_subgroup_to_prototype("landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "24")
util.regroup.set_subgroup_to_prototype("bio-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "25")
util.regroup.set_subgroup_to_prototype("he-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "26")
util.regroup.set_subgroup_to_prototype("incendiary-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "27")
util.regroup.set_subgroup_to_prototype("nuclear-landmine-capsule-ammo-rampant-arsenal", "combat-capsule", "28")

-- se-gun
util.regroup.set_subgroup_to_prototype("se-railgun", "combat-se-gun", "01")
util.regroup.set_subgroup_to_prototype("se-railgun-ammo", "combat-se-gun", "02")
util.regroup.set_subgroup_to_prototype("impulse-rifle", "combat-se-gun", "03")
util.regroup.set_subgroup_to_prototype("impulse-rifle-ammo", "combat-se-gun", "04")
util.regroup.set_subgroup_to_prototype("se-cryogun", "combat-se-gun", "05")
util.regroup.set_subgroup_to_prototype("se-cryogun-ammo", "combat-se-gun", "06")
util.regroup.set_subgroup_to_prototype("se-biogun", "combat-se-gun", "07")
util.regroup.set_subgroup_to_prototype("se-bloater-ammo", "combat-se-gun", "08")
util.regroup.set_subgroup_to_prototype("se-pheromone-ammo", "combat-se-gun", "09")
util.regroup.set_subgroup_to_prototype("se-tesla-gun", "combat-se-gun", "10")
util.regroup.set_subgroup_to_prototype("se-tesla-ammo", "combat-se-gun", "11")
util.regroup.set_subgroup_to_prototype("grappling-gun", "combat-se-gun", "12")
util.regroup.set_subgroup_to_prototype("grappling-gun-ammo", "combat-se-gun", "13")

-- cannon-shell
util.regroup.set_subgroup_to_prototype("cannon-item-rampant-arsenal", "combat-cannon", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-cannon-item-rampant-arsenal", "combat-cannon", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-cannon-item-rampant-arsenal", "combat-cannon", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-cannon-item-rampant-arsenal", "combat-cannon", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-cannon-item-rampant-arsenal", "combat-cannon", "014")
util.regroup.set_subgroup_to_prototype("rapid-cannon-item-rampant-arsenal", "combat-cannon", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-rapid-cannon-item-rampant-arsenal", "combat-cannon", "024")
util.regroup.set_subgroup_to_prototype("cannon-shell", "combat-cannon", "03")
util.regroup.set_subgroup_to_prototype("explosive-cannon-shell", "combat-cannon", "04")
util.regroup.set_subgroup_to_prototype("uranium-cannon-shell", "combat-cannon", "05")
util.regroup.set_subgroup_to_prototype("explosive-uranium-cannon-shell", "combat-cannon", "06")
util.regroup.set_subgroup_to_prototype("bio-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "07")
util.regroup.set_subgroup_to_prototype("he-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "08")
util.regroup.set_subgroup_to_prototype("incendiary-cannon-shell-ammo-rampant-arsenal", "combat-cannon", "09")

-- combat-rocket
util.regroup.set_subgroup_to_prototype("rocket-item-rampant-arsenal", "combat-rocket", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-rocket-item-rampant-arsenal", "combat-rocket", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-rocket-item-rampant-arsenal", "combat-rocket", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-rocket-item-rampant-arsenal", "combat-rocket", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-rocket-item-rampant-arsenal", "combat-rocket", "014")
util.regroup.set_subgroup_to_prototype("rapid-rocket-item-rampant-arsenal", "combat-rocket", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-rapid-rocket-item-rampant-arsenal", "combat-rocket", "024")
util.regroup.set_subgroup_to_prototype("rocket-launcher", "combat-rocket", "03")
util.regroup.set_subgroup_to_prototype("rocket-launcher-gun-rampant-arsenal", "combat-rocket", "04")
util.regroup.set_subgroup_to_prototype("heavy-rocket-launcher", "combat-rocket", "05")
util.regroup.set_subgroup_to_prototype("rocket", "combat-rocket", "06")
util.regroup.set_subgroup_to_prototype("explosive-rocket", "combat-rocket", "07")
util.regroup.set_subgroup_to_prototype("se-plague-bomb", "combat-rocket", "08")
util.regroup.set_subgroup_to_prototype("heavy-rocket", "combat-rocket", "09")
util.regroup.set_subgroup_to_prototype("atomic-bomb", "combat-rocket", "10")
util.regroup.set_subgroup_to_prototype("fi_atomic_bomb_recipe", "combat-rocket", "102")
util.regroup.set_subgroup_to_prototype("antimatter-rocket", "combat-rocket", "11")
util.regroup.set_subgroup_to_prototype("bio-rocket-ammo-rampant-arsenal", "combat-rocket", "12")
util.regroup.set_subgroup_to_prototype("he-rocket-ammo-rampant-arsenal", "combat-rocket", "13")
util.regroup.set_subgroup_to_prototype("incendiary-rocket-ammo-rampant-arsenal", "combat-rocket", "14")

-- combat-railgun
util.regroup.set_subgroup_to_prototype("kr-railgun-turret", "combat-railgun", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-kr-railgun-turret", "combat-railgun", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-kr-railgun-turret", "combat-railgun", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-kr-railgun-turret", "combat-railgun", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-kr-railgun-turret", "combat-railgun", "014")
util.regroup.set_subgroup_to_prototype("basic-railgun-shell", "combat-railgun", "02")
util.regroup.set_subgroup_to_prototype("explosion-railgun-shell", "combat-railgun", "03")
util.regroup.set_subgroup_to_prototype("antimatter-railgun-shell", "combat-railgun", "04")

-- combat-rocket-turret
util.regroup.set_subgroup_to_prototype("kr-rocket-turret", "combat-rocket-turret", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-kr-rocket-turret", "combat-rocket-turret", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-kr-rocket-turret", "combat-rocket-turret", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-kr-rocket-turret", "combat-rocket-turret", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-kr-rocket-turret", "combat-rocket-turret", "014")
util.regroup.set_subgroup_to_prototype("explosive-turret-rocket", "combat-rocket-turret", "02")
util.regroup.set_subgroup_to_prototype("nuclear-turret-rocket", "combat-rocket-turret", "03")
util.regroup.set_subgroup_to_prototype("antimatter-turret-rocket", "combat-rocket-turret", "04")

-- combat-laser
util.regroup.set_subgroup_to_prototype("laser-turret", "combat-laser", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-laser-turret", "combat-laser", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-laser-turret", "combat-laser", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-laser-turret", "combat-laser", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-laser-turret", "combat-laser", "014")
util.regroup.set_subgroup_to_prototype("lightning-item-rampant-arsenal", "combat-laser", "02")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-lightning-item-rampant-arsenal", "combat-laser", "021")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-lightning-item-rampant-arsenal", "combat-laser", "022")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-lightning-item-rampant-arsenal", "combat-laser", "023")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-lightning-item-rampant-arsenal", "combat-laser", "024")
util.regroup.set_subgroup_to_prototype("advanced-beam-item-rampant-arsenal", "combat-laser", "03")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-advanced-beam-item-rampant-arsenal", "combat-laser", "031")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-advanced-beam-item-rampant-arsenal", "combat-laser", "032")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-advanced-beam-item-rampant-arsenal", "combat-laser", "033")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-advanced-beam-item-rampant-arsenal", "combat-laser", "034")
util.regroup.set_subgroup_to_prototype("advanced-laser-item-rampant-arsenal", "combat-laser", "04")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-advanced-laser-item-rampant-arsenal", "combat-laser", "041")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-advanced-laser-item-rampant-arsenal", "combat-laser", "042")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-advanced-laser-item-rampant-arsenal", "combat-laser", "043")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-advanced-laser-item-rampant-arsenal", "combat-laser", "044")
util.regroup.set_subgroup_to_prototype("kr-laser-artillery-turret", "combat-laser", "05")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-kr-laser-artillery-turret", "combat-laser", "051")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-kr-laser-artillery-turret", "combat-laser", "052")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-kr-laser-artillery-turret", "combat-laser", "053")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-kr-laser-artillery-turret", "combat-laser", "054")

-- combat-artillery
util.regroup.set_subgroup_to_prototype("artillery-turret", "combat-artillery", "01")
util.regroup.set_subgroup_to_prototype("hero-turret-1-for-artillery-turret", "combat-artillery", "011")
util.regroup.set_subgroup_to_prototype("hero-turret-2-for-artillery-turret", "combat-artillery", "012")
util.regroup.set_subgroup_to_prototype("hero-turret-3-for-artillery-turret", "combat-artillery", "013")
util.regroup.set_subgroup_to_prototype("hero-turret-4-for-artillery-turret", "combat-artillery", "014")
util.regroup.set_subgroup_to_prototype("artillery-shell", "combat-artillery", "02")
util.regroup.set_subgroup_to_prototype("nuclear-artillery-shell", "combat-artillery", "03")
util.regroup.set_subgroup_to_prototype("antimatter-artillery-shell", "combat-artillery", "04")
util.regroup.set_subgroup_to_prototype("bio-artillery-ammo-rampant-arsenal", "combat-artillery", "05")
util.regroup.set_subgroup_to_prototype("he-artillery-ammo-rampant-arsenal", "combat-artillery", "06")
util.regroup.set_subgroup_to_prototype("incendiary-artillery-ammo-rampant-arsenal", "combat-artillery", "07")
util.regroup.set_subgroup_to_prototype("nuclear-artillery-ammo-rampant-arsenal", "combat-artillery", "08")

-- combat-surface-defense
util.regroup.set_subgroup_to_prototype("se-meteor-point-defence", "combat-surface-defense", "01")
util.regroup.set_subgroup_to_prototype("se-meteor-point-defence-ammo", "combat-surface-defense", "02")
util.regroup.set_subgroup_to_prototype("se-meteor-defence", "combat-surface-defense", "03")
util.regroup.set_subgroup_to_prototype("se-meteor-defence-ammo", "combat-surface-defense", "04")
util.regroup.set_subgroup_to_prototype("se-energy-beam-defence", "combat-surface-defense", "05")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-weapon", "combat-surface-defense", "06")
util.regroup.set_subgroup_to_prototype("se-delivery-cannon-weapon-capsule", "combat-surface-defense", "07")

-- combat-grenade
util.regroup.set_subgroup_to_prototype("grenade", "combat-grenade", "01")
util.regroup.set_subgroup_to_prototype("cluster-grenade", "combat-grenade", "02")
util.regroup.set_subgroup_to_prototype("el_grenade", "combat-grenade", "03")
util.regroup.set_subgroup_to_prototype("el_grenade_recipe", "combat-grenade", "04")
util.regroup.set_subgroup_to_prototype("fi_grenade", "combat-grenade", "05")
util.regroup.set_subgroup_to_prototype("fi_grenade_recipe", "combat-grenade", "06")
util.regroup.set_subgroup_to_prototype("fu_grenade", "combat-grenade", "07")
util.regroup.set_subgroup_to_prototype("fu_grenade_recipe", "combat-grenade", "08")
util.regroup.set_subgroup_to_prototype("bio-grenade-capsule-rampant-arsenal", "combat-grenade", "09")
util.regroup.set_subgroup_to_prototype("he-grenade-capsule-rampant-arsenal", "combat-grenade", "10")
util.regroup.set_subgroup_to_prototype("incendiary-grenade-capsule-rampant-arsenal", "combat-grenade", "11")
util.regroup.set_subgroup_to_prototype("poison-capsule", "combat-grenade", "12")
util.regroup.set_subgroup_to_prototype("toxic-capsule-rampant-arsenal", "combat-grenade", "13")
util.regroup.set_subgroup_to_prototype("paralysis-capsule-rampant-arsenal", "combat-grenade", "14")
util.regroup.set_subgroup_to_prototype("repair-capsule-rampant-arsenal", "combat-grenade", "15")
util.regroup.set_subgroup_to_prototype("healing-capsule-rampant-arsenal", "combat-grenade", "16")
util.regroup.set_subgroup_to_prototype("slowdown-capsule", "combat-grenade", "17")
util.regroup.set_subgroup_to_prototype("speed-capsule-rampant-arsenal", "combat-grenade", "18")
util.regroup.set_subgroup_to_prototype("kr-biter-virus", "combat-grenade", "19")
util.regroup.set_subgroup_to_prototype("kr-creep-virus", "combat-grenade", "20")
util.regroup.set_subgroup_to_prototype("cliff-explosives", "combat-grenade", "21")
util.regroup.set_subgroup_to_prototype("defender-capsule", "combat-grenade", "22")
util.regroup.set_subgroup_to_prototype("distractor-capsule", "combat-grenade", "23")
util.regroup.set_subgroup_to_prototype("destroyer-capsule", "combat-grenade", "24")

-- combat-biter-capsule
util.regroup.set_subgroup_to_prototype("se-capsule-small-biter", "combat-biter-capsule", "01")
util.regroup.set_subgroup_to_prototype("se-capsule-medium-biter", "combat-biter-capsule", "02")
util.regroup.set_subgroup_to_prototype("se-capsule-big-biter", "combat-biter-capsule", "03")
util.regroup.set_subgroup_to_prototype("se-capsule-behemoth-biter", "combat-biter-capsule", "04")
util.regroup.set_subgroup_to_prototype("se-capsule-small-spitter", "combat-biter-capsule", "05")
util.regroup.set_subgroup_to_prototype("se-capsule-medium-spitter", "combat-biter-capsule", "06")
util.regroup.set_subgroup_to_prototype("se-capsule-big-spitter", "combat-biter-capsule", "07")
util.regroup.set_subgroup_to_prototype("se-capsule-behemoth-spitter", "combat-biter-capsule", "08")
